<?php

$previous = require __DIR__ . '/server_5.7.php';

$new = [
	[
		"code"      => 1030,
		"symbol"    => "ER_GET_ERRNO",
		"sql_state" => "HY000",
		"template"  => "Got error {p1} - '{#p2}' from storage engine",
	],
	[
		"code"      => 1062,
		"symbol"    => "ER_DUP_ENTRY",
		"sql_state" => "23000",
		"template"  => "Duplicate entry '{#p1}' for key {p2}",
	],
	[
		"code"      => 1180,
		"symbol"    => "ER_ERROR_DURING_COMMIT",
		"sql_state" => "HY000",
		"template"  => "Got error {p1} - '{#p2}' during COMMIT",
	],
	[
		"code"      => 1181,
		"symbol"    => "ER_ERROR_DURING_ROLLBACK",
		"sql_state" => "HY000",
		"template"  => "Got error {p1} - '{#p2}' during ROLLBACK",
	],
	[
		"code"      => 1353,
		"symbol"    => "ER_VIEW_WRONG_LIST",
		"sql_state" => "HY000",
		"template"  => "In definition of view, derived table or common table expression, SELECT list and column names list have different column counts",
	],
	[
		"code"      => 1454,
		"symbol"    => "ER_TRG_NO_DEFINER",
		"sql_state" => "HY000",
		"template"  => "No definer attribute for trigger '{#p1}'.'{#p2}'. It's disallowed to create trigger without definer.",
	],
	[
		"code"      => 1558,
		"symbol"    => "ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE",
		"sql_state" => "HY000",
		"template"  => "The column count of mysql.{#p1} is wrong. Expected {p2}, found {p3}. Created with MySQL {p4}, now running {p5}. Please perform the MySQL upgrade procedure.",
	],
	[
		"code"      => 1579,
		"symbol"    => "ER_UNSUPORTED_LOG_ENGINE",
		"sql_state" => "HY000",
		"template"  => "This storage engine cannot be used for log tables",
	],
	[
		"code"      => 1627,
		"symbol"    => "ER_EXCEPTIONS_WRITE_ERROR",
		"sql_state" => "HY000",
		"template"  => "Write to exceptions table failed. Message: {#p1}",
	],
	[
		"code"      => 1789,
		"symbol"    => "ER_MASTER_HAS_PURGED_REQUIRED_GTIDS",
		"sql_state" => "HY000",
		"template"  => "Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. To find the missing transactions, see the master's error log or the manual for GTID_SUBTRACT.",
	],
	[
		"code"      => 1821,
		"symbol"    => "ER_FK_NO_INDEX_CHILD",
		"sql_state" => "HY000",
		"template"  => "Failed to add the foreign key constraint. Missing index for constraint '{#p1}' in the foreign table '{#p2}'",
	],
	[
		"code"      => 1822,
		"symbol"    => "ER_FK_NO_INDEX_PARENT",
		"sql_state" => "HY000",
		"template"  => "Failed to add the foreign key constraint. Missing index for constraint '{#p1}' in the referenced table '{#p2}'",
	],
	[
		"code"      => 1827,
		"symbol"    => "ER_PASSWORD_FORMAT",
		"sql_state" => "HY000",
		"template"  => "The password hash doesn't have the expected format.",
	],
	[
		"code"      => 1881,
		"symbol"    => "ER_INNODB_FORCED_RECOVERY",
		"sql_state" => "HY000",
		"template"  => "Operation not allowed when innodb_force_recovery > 0.",
	],
	[
		"code"      => 3009,
		"symbol"    => "ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE_V2",
		"sql_state" => "HY000",
		"template"  => "The column count of {#p1}.{#p2} is wrong. Expected {p3}, found {p4}. Created with MySQL {p5}, now running {p6}. Please perform the MySQL upgrade procedure.",
	],
	[
		"code"      => 3035,
		"symbol"    => "ER_GIS_UNKNOWN_ERROR",
		"sql_state" => "HY000",
		"template"  => "Unknown GIS error occurred in function {#p1}.",
	],
	[
		"code"      => 3049,
		"symbol"    => "ER_STD_OVERFLOW_ERROR",
		"sql_state" => "HY000",
		"template"  => "Overflow error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3149,
		"symbol"    => "ER_INVALID_JSON_PATH_WILDCARD",
		"sql_state" => "42000",
		"template"  => "In this situation, path expressions may not contain the * and ** tokens or an array range.",
	],
	[
		"code"      => 3152,
		"symbol"    => "ER_JSON_USED_AS_KEY",
		"sql_state" => "42000",
		"template"  => "JSON column '{#p1}' supports indexing only via generated columns on a specified JSON path.",
	],
	[
		"code"      => 3162,
		"symbol"    => "ER_USER_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "Authorization ID {#p1} does not exist.",
	],
	[
		"code"      => 3163,
		"symbol"    => "ER_USER_ALREADY_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Authorization ID {#p1} already exists.",
	],
	[
		"code"      => 3189,
		"symbol"    => "ER_USER_COLUMN_OLD_LENGTH",
		"sql_state" => "HY000",
		"template"  => "It seems that your db schema is old. The {#p1} column is 77 characters long and should be 93 characters long. Please perform the MySQL upgrade procedure.",
	],
	[
		"code"      => 3500,
		"symbol"    => "ER_UNSUPPORT_COMPRESSED_TEMPORARY_TABLE",
		"sql_state" => "HY000",
		"template"  => "CREATE TEMPORARY TABLE is not allowed with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.",
	],
	[
		"code"      => 3501,
		"symbol"    => "ER_ACL_OPERATION_FAILED",
		"sql_state" => "HY000",
		"template"  => "The ACL operation failed due to the following error from SE: errcode {p1} - {#p2}",
	],
	[
		"code"      => 3502,
		"symbol"    => "ER_UNSUPPORTED_INDEX_ALGORITHM",
		"sql_state" => "HY000",
		"template"  => "This storage engine does not support the {#p1} index algorithm, storage engine default was used instead.",
	],
	[
		"code"      => 3503,
		"symbol"    => "ER_NO_SUCH_DB",
		"sql_state" => "42Y07",
		"template"  => "Database '{#p1}' doesn't exist",
	],
	[
		"code"      => 3504,
		"symbol"    => "ER_TOO_BIG_ENUM",
		"sql_state" => "HY000",
		"template"  => "Too many enumeration values for column {#p1}.",
	],
	[
		"code"      => 3505,
		"symbol"    => "ER_TOO_LONG_SET_ENUM_VALUE",
		"sql_state" => "HY000",
		"template"  => "Too long enumeration/set value for column {#p1}.",
	],
	[
		"code"      => 3506,
		"symbol"    => "ER_INVALID_DD_OBJECT",
		"sql_state" => "HY000",
		"template"  => "{#p1} dictionary object is invalid. ({#p2})",
	],
	[
		"code"      => 3507,
		"symbol"    => "ER_UPDATING_DD_TABLE",
		"sql_state" => "HY000",
		"template"  => "Failed to update {#p1} dictionary object.",
	],
	[
		"code"      => 3508,
		"symbol"    => "ER_INVALID_DD_OBJECT_ID",
		"sql_state" => "HY000",
		"template"  => "Dictionary object id ({p1}) does not exist.",
	],
	[
		"code"      => 3509,
		"symbol"    => "ER_INVALID_DD_OBJECT_NAME",
		"sql_state" => "HY000",
		"template"  => "Dictionary object name '{#p1}' is invalid. ({#p2})",
	],
	[
		"code"      => 3510,
		"symbol"    => "ER_TABLESPACE_MISSING_WITH_NAME",
		"sql_state" => "HY000",
		"template"  => "Tablespace {#p1} doesn't exist.",
	],
	[
		"code"      => 3511,
		"symbol"    => "ER_TOO_LONG_ROUTINE_COMMENT",
		"sql_state" => "HY000",
		"template"  => "Comment for routine '{#p1}' is too long (max = {p2})",
	],
	[
		"code"      => 3512,
		"symbol"    => "ER_SP_LOAD_FAILED",
		"sql_state" => "HY000",
		"template"  => "Failed to load routine '{#p1}'.",
	],
	[
		"code"      => 3513,
		"symbol"    => "ER_INVALID_BITWISE_OPERANDS_SIZE",
		"sql_state" => "HY000",
		"template"  => "Binary operands of bitwise operators must be of equal length",
	],
	[
		"code"      => 3514,
		"symbol"    => "ER_INVALID_BITWISE_AGGREGATE_OPERANDS_SIZE",
		"sql_state" => "HY000",
		"template"  => "Aggregate bitwise functions cannot accept arguments longer than 511 bytes; consider using the SUBSTRING() function",
	],
	[
		"code"      => 3515,
		"symbol"    => "ER_WARN_UNSUPPORTED_HINT",
		"sql_state" => "HY000",
		"template"  => "Hints aren't supported in {#p1}",
	],
	[
		"code"      => 3517,
		"symbol"    => "ER_SRS_PARSE_ERROR",
		"sql_state" => "SR002",
		"template"  => "Can't parse the spatial reference system definition of SRID {p1}.",
	],
	[
		"code"      => 3518,
		"symbol"    => "ER_SRS_PROJ_PARAMETER_MISSING",
		"sql_state" => "SR003",
		"template"  => "The spatial reference system definition for SRID {p1} does not specify the mandatory {#p2} (EPSG {p3}) projection parameter.",
	],
	[
		"code"      => 3519,
		"symbol"    => "ER_WARN_SRS_NOT_FOUND",
		"sql_state" => "01000",
		"template"  => "There's no spatial reference system with SRID {p1}.",
	],
	[
		"code"      => 3520,
		"symbol"    => "ER_SRS_NOT_CARTESIAN",
		"sql_state" => "22S00",
		"template"  => "Function {#p1} is only defined for Cartesian spatial reference systems, but one of its arguments is in SRID {p2}, which is not Cartesian.",
	],
	[
		"code"      => 3521,
		"symbol"    => "ER_SRS_NOT_CARTESIAN_UNDEFINED",
		"sql_state" => "SR001",
		"template"  => "Function {#p1} is only defined for Cartesian spatial reference systems, but one of its arguments is in SRID {p2}, which has not been defined.",
	],
	[
		"code"      => 3522,
		"symbol"    => "ER_PK_INDEX_CANT_BE_INVISIBLE",
		"sql_state" => "HY000",
		"template"  => "A primary key index cannot be invisible",
	],
	[
		"code"      => 3523,
		"symbol"    => "ER_UNKNOWN_AUTHID",
		"sql_state" => "HY000",
		"template"  => "Unknown authorization ID `{#p1}`@`{#p2}`",
	],
	[
		"code"      => 3524,
		"symbol"    => "ER_FAILED_ROLE_GRANT",
		"sql_state" => "HY000",
		"template"  => "Failed to grant {#p1}` to {#p2}",
	],
	[
		"code"      => 3525,
		"symbol"    => "ER_OPEN_ROLE_TABLES",
		"sql_state" => "HY000",
		"template"  => "Failed to open the security system tables",
	],
	[
		"code"      => 3526,
		"symbol"    => "ER_FAILED_DEFAULT_ROLES",
		"sql_state" => "HY000",
		"template"  => "Failed to set default roles",
	],
	[
		"code"      => 3527,
		"symbol"    => "ER_COMPONENTS_NO_SCHEME",
		"sql_state" => "HY000",
		"template"  => "Cannot find schema in specified URN: '{#p1}'.",
	],
	[
		"code"      => 3528,
		"symbol"    => "ER_COMPONENTS_NO_SCHEME_SERVICE",
		"sql_state" => "HY000",
		"template"  => "Cannot acquire scheme load service implementation for schema '{#p1}' in specified URN: '{#p2}'.",
	],
	[
		"code"      => 3529,
		"symbol"    => "ER_COMPONENTS_CANT_LOAD",
		"sql_state" => "HY000",
		"template"  => "Cannot load component from specified URN: '{#p1}'.",
	],
	[
		"code"      => 3530,
		"symbol"    => "ER_ROLE_NOT_GRANTED",
		"sql_state" => "HY000",
		"template"  => "`{#p1}`@`{#p2}` is not granted to `{#p3}`@`{#p4}`",
	],
	[
		"code"      => 3531,
		"symbol"    => "ER_FAILED_REVOKE_ROLE",
		"sql_state" => "HY000",
		"template"  => "Could not revoke role from `{#p1}`@`{#p2}`",
	],
	[
		"code"      => 3532,
		"symbol"    => "ER_RENAME_ROLE",
		"sql_state" => "HY000",
		"template"  => "Renaming of a role identifier is forbidden",
	],
	[
		"code"      => 3533,
		"symbol"    => "ER_COMPONENTS_CANT_ACQUIRE_SERVICE_IMPLEMENTATION",
		"sql_state" => "HY000",
		"template"  => "Cannot acquire specified service implementation: '{#p1}'.",
	],
	[
		"code"      => 3534,
		"symbol"    => "ER_COMPONENTS_CANT_SATISFY_DEPENDENCY",
		"sql_state" => "HY000",
		"template"  => "Cannot satisfy dependency for service '{#p1}' required by component '{#p2}'.",
	],
	[
		"code"      => 3535,
		"symbol"    => "ER_COMPONENTS_LOAD_CANT_REGISTER_SERVICE_IMPLEMENTATION",
		"sql_state" => "HY000",
		"template"  => "Cannot register service implementation '{#p1}' provided by component '{#p2}'.",
	],
	[
		"code"      => 3536,
		"symbol"    => "ER_COMPONENTS_LOAD_CANT_INITIALIZE",
		"sql_state" => "HY000",
		"template"  => "Initialization method provided by component '{#p1}' failed.",
	],
	[
		"code"      => 3537,
		"symbol"    => "ER_COMPONENTS_UNLOAD_NOT_LOADED",
		"sql_state" => "HY000",
		"template"  => "Component specified by URN '{#p1}' to unload has not been loaded before.",
	],
	[
		"code"      => 3538,
		"symbol"    => "ER_COMPONENTS_UNLOAD_CANT_DEINITIALIZE",
		"sql_state" => "HY000",
		"template"  => "De-initialization method provided by component '{#p1}' failed.",
	],
	[
		"code"      => 3539,
		"symbol"    => "ER_COMPONENTS_CANT_RELEASE_SERVICE",
		"sql_state" => "HY000",
		"template"  => "Release of previously acquired service implementation failed.",
	],
	[
		"code"      => 3540,
		"symbol"    => "ER_COMPONENTS_UNLOAD_CANT_UNREGISTER_SERVICE",
		"sql_state" => "HY000",
		"template"  => "Unregistration of service implementation '{#p1}' provided by component '{#p2}' failed during unloading of the component.",
	],
	[
		"code"      => 3541,
		"symbol"    => "ER_COMPONENTS_CANT_UNLOAD",
		"sql_state" => "HY000",
		"template"  => "Cannot unload component from specified URN: '{#p1}'.",
	],
	[
		"code"      => 3542,
		"symbol"    => "ER_WARN_UNLOAD_THE_NOT_PERSISTED",
		"sql_state" => "HY000",
		"template"  => "The Persistent Dynamic Loader was used to unload a component '{#p1}', but it was not used to load that component before.",
	],
	[
		"code"      => 3543,
		"symbol"    => "ER_COMPONENT_TABLE_INCORRECT",
		"sql_state" => "HY000",
		"template"  => "The mysql.component table is missing or has an incorrect definition.",
	],
	[
		"code"      => 3544,
		"symbol"    => "ER_COMPONENT_MANIPULATE_ROW_FAILED",
		"sql_state" => "HY000",
		"template"  => "Failed to manipulate component '{#p1}' persistence data. Error code {p2} from storage engine.",
	],
	[
		"code"      => 3545,
		"symbol"    => "ER_COMPONENTS_UNLOAD_DUPLICATE_IN_GROUP",
		"sql_state" => "HY000",
		"template"  => "The component with specified URN: '{#p1}' was specified in group more than once.",
	],
	[
		"code"      => 3546,
		"symbol"    => "ER_CANT_SET_GTID_PURGED_DUE_SETS_CONSTRAINTS",
		"sql_state" => "HY000",
		"template"  => "@@GLOBAL.GTID_PURGED cannot be changed: {#p1}",
	],
	[
		"code"      => 3547,
		"symbol"    => "ER_CANNOT_LOCK_USER_MANAGEMENT_CACHES",
		"sql_state" => "HY000",
		"template"  => "Can not lock user management caches for processing.",
	],
	[
		"code"      => 3548,
		"symbol"    => "ER_SRS_NOT_FOUND",
		"sql_state" => "SR001",
		"template"  => "There's no spatial reference system with SRID {p1}.",
	],
	[
		"code"      => 3549,
		"symbol"    => "ER_VARIABLE_NOT_PERSISTED",
		"sql_state" => "HY000",
		"template"  => "Variables cannot be persisted. Please retry.",
	],
	[
		"code"      => 3550,
		"symbol"    => "ER_IS_QUERY_INVALID_CLAUSE",
		"sql_state" => "HY000",
		"template"  => "Information schema queries do not support the '{#p1}' clause.",
	],
	[
		"code"      => 3551,
		"symbol"    => "ER_UNABLE_TO_STORE_STATISTICS",
		"sql_state" => "HY000",
		"template"  => "Unable to store dynamic {#p1} statistics into data dictionary.",
	],
	[
		"code"      => 3552,
		"symbol"    => "ER_NO_SYSTEM_SCHEMA_ACCESS",
		"sql_state" => "HY000",
		"template"  => "Access to system schema '{#p1}' is rejected.",
	],
	[
		"code"      => 3553,
		"symbol"    => "ER_NO_SYSTEM_TABLESPACE_ACCESS",
		"sql_state" => "HY000",
		"template"  => "Access to system tablespace '{#p1}' is rejected.",
	],
	[
		"code"      => 3554,
		"symbol"    => "ER_NO_SYSTEM_TABLE_ACCESS",
		"sql_state" => "HY000",
		"template"  => "Access to {#p1} '{#p2}.{#p3}' is rejected.",
	],
	[
		"code"      => 3555,
		"symbol"    => "ER_NO_SYSTEM_TABLE_ACCESS_FOR_DICTIONARY_TABLE",
		"sql_state" => "HY000",
		"template"  => "data dictionary table",
	],
	[
		"code"      => 3556,
		"symbol"    => "ER_NO_SYSTEM_TABLE_ACCESS_FOR_SYSTEM_TABLE",
		"sql_state" => "HY000",
		"template"  => "system table",
	],
	[
		"code"      => 3557,
		"symbol"    => "ER_NO_SYSTEM_TABLE_ACCESS_FOR_TABLE",
		"sql_state" => "HY000",
		"template"  => "table",
	],
	[
		"code"      => 3558,
		"symbol"    => "ER_INVALID_OPTION_KEY",
		"sql_state" => "22023",
		"template"  => "Invalid option key '{#p1}' in function {#p2}.",
	],
	[
		"code"      => 3559,
		"symbol"    => "ER_INVALID_OPTION_VALUE",
		"sql_state" => "22023",
		"template"  => "Invalid value '{#p1}' for option '{#p2}' in function '{#p3}'.",
	],
	[
		"code"      => 3560,
		"symbol"    => "ER_INVALID_OPTION_KEY_VALUE_PAIR",
		"sql_state" => "22023",
		"template"  => "The string '{#p1}' is not a valid key {p2} value pair in function {#p3}.",
	],
	[
		"code"      => 3561,
		"symbol"    => "ER_INVALID_OPTION_START_CHARACTER",
		"sql_state" => "22023",
		"template"  => "The options argument in function {#p1} starts with the invalid character '{p2}'.",
	],
	[
		"code"      => 3562,
		"symbol"    => "ER_INVALID_OPTION_END_CHARACTER",
		"sql_state" => "22023",
		"template"  => "The options argument in function {#p1} ends with the invalid character '{p2}'.",
	],
	[
		"code"      => 3563,
		"symbol"    => "ER_INVALID_OPTION_CHARACTERS",
		"sql_state" => "22023",
		"template"  => "The options argument in function {#p1} contains the invalid character sequence '{#p2}'.",
	],
	[
		"code"      => 3564,
		"symbol"    => "ER_DUPLICATE_OPTION_KEY",
		"sql_state" => "22023",
		"template"  => "Duplicate option key '{#p1}' in funtion '{#p2}'.",
	],
	[
		"code"      => 3565,
		"symbol"    => "ER_WARN_SRS_NOT_FOUND_AXIS_ORDER",
		"sql_state" => "01000",
		"template"  => "There's no spatial reference system with SRID {p1}. The axis order is unknown.",
	],
	[
		"code"      => 3566,
		"symbol"    => "ER_NO_ACCESS_TO_NATIVE_FCT",
		"sql_state" => "HY000",
		"template"  => "Access to native function '{#p1}' is rejected.",
	],
	[
		"code"      => 3567,
		"symbol"    => "ER_RESET_MASTER_TO_VALUE_OUT_OF_RANGE",
		"sql_state" => "HY000",
		"template"  => "The requested value '{p1}' for the next binary log index is out of range. Please use a value between '1' and '{p2}'.",
	],
	[
		"code"      => 3568,
		"symbol"    => "ER_UNRESOLVED_TABLE_LOCK",
		"sql_state" => "HY000",
		"template"  => "Unresolved table name {#p1} in locking clause.",
	],
	[
		"code"      => 3569,
		"symbol"    => "ER_DUPLICATE_TABLE_LOCK",
		"sql_state" => "HY000",
		"template"  => "Table {#p1} appears in multiple locking clauses.",
	],
	[
		"code"      => 3570,
		"symbol"    => "ER_BINLOG_UNSAFE_SKIP_LOCKED",
		"sql_state" => "HY000",
		"template"  => "Statement is unsafe because it uses SKIP LOCKED. The set of inserted values is non-deterministic.",
	],
	[
		"code"      => 3571,
		"symbol"    => "ER_BINLOG_UNSAFE_NOWAIT",
		"sql_state" => "HY000",
		"template"  => "Statement is unsafe because it uses NOWAIT. Whether the command will succeed or fail is not deterministic.",
	],
	[
		"code"      => 3572,
		"symbol"    => "ER_LOCK_NOWAIT",
		"sql_state" => "HY000",
		"template"  => "Statement aborted because lock(s) could not be acquired immediately and NOWAIT is set.",
	],
	[
		"code"      => 3573,
		"symbol"    => "ER_CTE_RECURSIVE_REQUIRES_UNION",
		"sql_state" => "HY000",
		"template"  => "Recursive Common Table Expression '{#p1}' should contain a UNION",
	],
	[
		"code"      => 3574,
		"symbol"    => "ER_CTE_RECURSIVE_REQUIRES_NONRECURSIVE_FIRST",
		"sql_state" => "HY000",
		"template"  => "Recursive Common Table Expression '{#p1}' should have one or more non-recursive query blocks followed by one or more recursive ones",
	],
	[
		"code"      => 3575,
		"symbol"    => "ER_CTE_RECURSIVE_FORBIDS_AGGREGATION",
		"sql_state" => "HY000",
		"template"  => "Recursive Common Table Expression '{#p1}' can contain neither aggregation nor window functions in recursive query block",
	],
	[
		"code"      => 3576,
		"symbol"    => "ER_CTE_RECURSIVE_FORBIDDEN_JOIN_ORDER",
		"sql_state" => "HY000",
		"template"  => "In recursive query block of Recursive Common Table Expression '{#p1}', the recursive table must neither be in the right argument of a LEFT JOIN, nor be forced to be non-first with join order hints",
	],
	[
		"code"      => 3577,
		"symbol"    => "ER_CTE_RECURSIVE_REQUIRES_SINGLE_REFERENCE",
		"sql_state" => "HY000",
		"template"  => "In recursive query block of Recursive Common Table Expression '{#p1}', the recursive table must be referenced only once, and not in any subquery",
	],
	[
		"code"      => 3578,
		"symbol"    => "ER_SWITCH_TMP_ENGINE",
		"sql_state" => "HY000",
		"template"  => "'{#p1}' requires @@internal_tmp_disk_storage_engine=InnoDB",
	],
	[
		"code"      => 3579,
		"symbol"    => "ER_WINDOW_NO_SUCH_WINDOW",
		"sql_state" => "HY000",
		"template"  => "Window name '{#p1}' is not defined.",
	],
	[
		"code"      => 3580,
		"symbol"    => "ER_WINDOW_CIRCULARITY_IN_WINDOW_GRAPH",
		"sql_state" => "HY000",
		"template"  => "There is a circularity in the window dependency graph.",
	],
	[
		"code"      => 3581,
		"symbol"    => "ER_WINDOW_NO_CHILD_PARTITIONING",
		"sql_state" => "HY000",
		"template"  => "A window which depends on another cannot define partitioning.",
	],
	[
		"code"      => 3582,
		"symbol"    => "ER_WINDOW_NO_INHERIT_FRAME",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' has a frame definition, so cannot be referenced by another window.",
	],
	[
		"code"      => 3583,
		"symbol"    => "ER_WINDOW_NO_REDEFINE_ORDER_BY",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' cannot inherit '{#p2}' since both contain an ORDER BY clause.",
	],
	[
		"code"      => 3584,
		"symbol"    => "ER_WINDOW_FRAME_START_ILLEGAL",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}': frame start cannot be UNBOUNDED FOLLOWING.",
	],
	[
		"code"      => 3585,
		"symbol"    => "ER_WINDOW_FRAME_END_ILLEGAL",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}': frame end cannot be UNBOUNDED PRECEDING.",
	],
	[
		"code"      => 3586,
		"symbol"    => "ER_WINDOW_FRAME_ILLEGAL",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}': frame start or end is negative, NULL or of non-integral type",
	],
	[
		"code"      => 3587,
		"symbol"    => "ER_WINDOW_RANGE_FRAME_ORDER_TYPE",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' with RANGE N PRECEDING/FOLLOWING frame requires exactly one ORDER BY expression, of numeric or temporal type",
	],
	[
		"code"      => 3588,
		"symbol"    => "ER_WINDOW_RANGE_FRAME_TEMPORAL_TYPE",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' with RANGE frame has ORDER BY expression of datetime type. Only INTERVAL bound value allowed.",
	],
	[
		"code"      => 3589,
		"symbol"    => "ER_WINDOW_RANGE_FRAME_NUMERIC_TYPE",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' with RANGE frame has ORDER BY expression of numeric type, INTERVAL bound value not allowed.",
	],
	[
		"code"      => 3590,
		"symbol"    => "ER_WINDOW_RANGE_BOUND_NOT_CONSTANT",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' has a non-constant frame bound.",
	],
	[
		"code"      => 3591,
		"symbol"    => "ER_WINDOW_DUPLICATE_NAME",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}' is defined twice.",
	],
	[
		"code"      => 3592,
		"symbol"    => "ER_WINDOW_ILLEGAL_ORDER_BY",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}': ORDER BY or PARTITION BY uses legacy position indication which is not supported, use expression.",
	],
	[
		"code"      => 3593,
		"symbol"    => "ER_WINDOW_INVALID_WINDOW_FUNC_USE",
		"sql_state" => "HY000",
		"template"  => "You cannot use the window function '{#p1}' in this context.'",
	],
	[
		"code"      => 3594,
		"symbol"    => "ER_WINDOW_INVALID_WINDOW_FUNC_ALIAS_USE",
		"sql_state" => "HY000",
		"template"  => "You cannot use the alias '{#p1}' of an expression containing a window function in this context.'",
	],
	[
		"code"      => 3595,
		"symbol"    => "ER_WINDOW_NESTED_WINDOW_FUNC_USE_IN_WINDOW_SPEC",
		"sql_state" => "HY000",
		"template"  => "You cannot nest a window function in the specification of window '{#p1}'.",
	],
	[
		"code"      => 3596,
		"symbol"    => "ER_WINDOW_ROWS_INTERVAL_USE",
		"sql_state" => "HY000",
		"template"  => "Window '{#p1}': INTERVAL can only be used with RANGE frames.",
	],
	[
		"code"      => 3597,
		"symbol"    => "ER_WINDOW_NO_GROUP_ORDER",
		"sql_state" => "HY000",
		"template"  => "ASC or DESC with GROUP BY isn't allowed with window functions; put ASC or DESC in ORDER BY",
	],
	[
		"code"      => 3597,
		"symbol"    => "ER_WINDOW_NO_GROUP_ORDER_UNUSED",
		"sql_state" => "HY000",
		"template"  => "ASC or DESC with GROUP BY isn't allowed with window functions; put ASC or DESC in ORDER BY",
	],
	[
		"code"      => 3598,
		"symbol"    => "ER_WINDOW_EXPLAIN_JSON",
		"sql_state" => "HY000",
		"template"  => "To get information about window functions use EXPLAIN FORMAT=JSON",
	],
	[
		"code"      => 3599,
		"symbol"    => "ER_WINDOW_FUNCTION_IGNORES_FRAME",
		"sql_state" => "HY000",
		"template"  => "Window function '{#p1}' ignores the frame clause of window '{#p2}' and aggregates over the whole partition",
	],
	[
		"code"      => 3600,
		"symbol"    => "ER_WINDOW_SE_NOT_ACCEPTABLE",
		"sql_state" => "HY000",
		"template"  => "Windowing requires @@internal_tmp_mem_storage_engine=TempTable.",
	],
	[
		"code"      => 3600,
		"symbol"    => "ER_WL9236_NOW_UNUSED",
		"sql_state" => "HY000",
		"template"  => "Windowing requires @@internal_tmp_mem_storage_engine=TempTable.",
	],
	[
		"code"      => 3601,
		"symbol"    => "ER_INVALID_NO_OF_ARGS",
		"sql_state" => "HY000",
		"template"  => "Too many arguments for function {#p1}: {p2}; maximum allowed is {#p3}.",
	],
	[
		"code"      => 3602,
		"symbol"    => "ER_FIELD_IN_GROUPING_NOT_GROUP_BY",
		"sql_state" => "HY000",
		"template"  => "Argument #{p1} of GROUPING function is not in GROUP BY",
	],
	[
		"code"      => 3603,
		"symbol"    => "ER_TOO_LONG_TABLESPACE_COMMENT",
		"sql_state" => "HY000",
		"template"  => "Comment for tablespace '{#p1}' is too long (max = {p2})",
	],
	[
		"code"      => 3604,
		"symbol"    => "ER_ENGINE_CANT_DROP_TABLE",
		"sql_state" => "HY000",
		"template"  => "Storage engine can't drop table '{#p1}'",
	],
	[
		"code"      => 3605,
		"symbol"    => "ER_ENGINE_CANT_DROP_MISSING_TABLE",
		"sql_state" => "HY000",
		"template"  => "Storage engine can't drop table '{#p1}' because it is missing. Use DROP TABLE IF EXISTS to remove it from data-dictionary.",
	],
	[
		"code"      => 3606,
		"symbol"    => "ER_TABLESPACE_DUP_FILENAME",
		"sql_state" => "HY000",
		"template"  => "Duplicate file name for tablespace '{#p1}'",
	],
	[
		"code"      => 3607,
		"symbol"    => "ER_DB_DROP_RMDIR2",
		"sql_state" => "HY000",
		"template"  => "Problem while dropping database. Can't remove database directory ({#p1}). Please remove it manually.",
	],
	[
		"code"      => 3608,
		"symbol"    => "ER_IMP_NO_FILES_MATCHED",
		"sql_state" => "HY000",
		"template"  => "No SDI files matched the pattern '{#p1}'",
	],
	[
		"code"      => 3609,
		"symbol"    => "ER_IMP_SCHEMA_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "Schema '{#p1}', referenced in SDI, does not exist.",
	],
	[
		"code"      => 3610,
		"symbol"    => "ER_IMP_TABLE_ALREADY_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Table '{#p1}.{#p2}', referenced in SDI, already exists.",
	],
	[
		"code"      => 3611,
		"symbol"    => "ER_IMP_INCOMPATIBLE_MYSQLD_VERSION",
		"sql_state" => "HY000",
		"template"  => "Imported mysqld_version ({p1}) is not compatible with current ({p2})",
	],
	[
		"code"      => 3612,
		"symbol"    => "ER_IMP_INCOMPATIBLE_DD_VERSION",
		"sql_state" => "HY000",
		"template"  => "Imported dd version ({p1}) is not compatible with current ({p2})",
	],
	[
		"code"      => 3613,
		"symbol"    => "ER_IMP_INCOMPATIBLE_SDI_VERSION",
		"sql_state" => "HY000",
		"template"  => "Imported sdi version ({p1}) is not compatible with current ({p2})",
	],
	[
		"code"      => 3614,
		"symbol"    => "ER_WARN_INVALID_HINT",
		"sql_state" => "HY000",
		"template"  => "Invalid number of arguments for hint {#p1}",
	],
	[
		"code"      => 3615,
		"symbol"    => "ER_VAR_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "Variable {#p1} does not exist in persisted config file",
	],
	[
		"code"      => 3616,
		"symbol"    => "ER_LONGITUDE_OUT_OF_RANGE",
		"sql_state" => "22S02",
		"template"  => "Longitude {p1} is out of range in function {#p2}. It must be within ({p3}, {p4}].",
	],
	[
		"code"      => 3617,
		"symbol"    => "ER_LATITUDE_OUT_OF_RANGE",
		"sql_state" => "22S03",
		"template"  => "Latitude {p1} is out of range in function {#p2}. It must be within [{p3}, {p4}].",
	],
	[
		"code"      => 3618,
		"symbol"    => "ER_NOT_IMPLEMENTED_FOR_GEOGRAPHIC_SRS",
		"sql_state" => "22S00",
		"template"  => "{#p1}({#p2}) has not been implemented for geographic spatial reference systems.",
	],
	[
		"code"      => 3619,
		"symbol"    => "ER_ILLEGAL_PRIVILEGE_LEVEL",
		"sql_state" => "HY000",
		"template"  => "Illegal privilege level specified for {#p1}",
	],
	[
		"code"      => 3620,
		"symbol"    => "ER_NO_SYSTEM_VIEW_ACCESS",
		"sql_state" => "HY000",
		"template"  => "Access to system view INFORMATION_SCHEMA.'{#p1}' is rejected.",
	],
	[
		"code"      => 3621,
		"symbol"    => "ER_COMPONENT_FILTER_FLABBERGASTED",
		"sql_state" => "HY000",
		"template"  => "The log-filter component \"{#p1}\" got confused at \"{#p2}\" ...",
	],
	[
		"code"      => 3622,
		"symbol"    => "ER_PART_EXPR_TOO_LONG",
		"sql_state" => "HY000",
		"template"  => "Partitioning expression is too long.",
	],
	[
		"code"      => 3623,
		"symbol"    => "ER_UDF_DROP_DYNAMICALLY_REGISTERED",
		"sql_state" => "HY000",
		"template"  => "DROP FUNCTION can't drop a dynamically registered user defined function",
	],
	[
		"code"      => 3624,
		"symbol"    => "ER_UNABLE_TO_STORE_COLUMN_STATISTICS",
		"sql_state" => "HY000",
		"template"  => "Unable to store column statistics for column '{#p1}' in table '{#p2}'.'{#p3}'",
	],
	[
		"code"      => 3625,
		"symbol"    => "ER_UNABLE_TO_UPDATE_COLUMN_STATISTICS",
		"sql_state" => "HY000",
		"template"  => "Unable to update column statistics for column '{#p1}' in table '{#p2}'.'{#p3}'",
	],
	[
		"code"      => 3626,
		"symbol"    => "ER_UNABLE_TO_DROP_COLUMN_STATISTICS",
		"sql_state" => "HY000",
		"template"  => "Unable to remove column statistics for column '{#p1}' in table '{#p2}'.'{#p3}'",
	],
	[
		"code"      => 3627,
		"symbol"    => "ER_UNABLE_TO_BUILD_HISTOGRAM",
		"sql_state" => "HY000",
		"template"  => "Unable to build histogram statistics for column '{#p1}' in table '{#p2}'.'{#p3}'",
	],
	[
		"code"      => 3628,
		"symbol"    => "ER_MANDATORY_ROLE",
		"sql_state" => "HY000",
		"template"  => "The role {#p1} is a mandatory role and can't be revoked or dropped. The restriction can be lifted by excluding the role identifier from the global variable mandatory_roles.",
	],
	[
		"code"      => 3629,
		"symbol"    => "ER_MISSING_TABLESPACE_FILE",
		"sql_state" => "HY000",
		"template"  => "Tablespace '{#p1}' does not have a file named '{#p2}'",
	],
	[
		"code"      => 3631,
		"symbol"    => "ER_CMD_NEED_SUPER",
		"sql_state" => "HY000",
		"template"  => "You need the SUPER privilege for command '{#p1}'",
	],
	[
		"code"      => 3632,
		"symbol"    => "ER_PATH_IN_DATADIR",
		"sql_state" => "HY000",
		"template"  => "Path is within the current data directory '{#p1}'",
	],
	[
		"code"      => 3633,
		"symbol"    => "ER_DDL_IN_PROGRESS",
		"sql_state" => "HY000",
		"template"  => "Concurrent DDL is performed during the operation. Please try again.",
	],
	[
		"code"      => 3633,
		"symbol"    => "ER_CLONE_DDL_IN_PROGRESS",
		"sql_state" => "HY000",
		"template"  => "Concurrent DDL is performed during clone operation. Please try again.",
	],
	[
		"code"      => 3634,
		"symbol"    => "ER_TOO_MANY_CONCURRENT_CLONES",
		"sql_state" => "HY000",
		"template"  => "Too many concurrent clone operations. Maximum allowed - {p1}.",
	],
	[
		"code"      => 3634,
		"symbol"    => "ER_CLONE_TOO_MANY_CONCURRENT_CLONES",
		"sql_state" => "HY000",
		"template"  => "Too many concurrent clone operations. Maximum allowed - {p1}.",
	],
	[
		"code"      => 3635,
		"symbol"    => "ER_APPLIER_LOG_EVENT_VALIDATION_ERROR",
		"sql_state" => "HY000",
		"template"  => "The table in transaction {#p1} does not comply with the requirements by an external plugin.",
	],
	[
		"code"      => 3636,
		"symbol"    => "ER_CTE_MAX_RECURSION_DEPTH",
		"sql_state" => "HY000",
		"template"  => "Recursive query aborted after {p1} iterations. Try increasing @@cte_max_recursion_depth to a larger value.",
	],
	[
		"code"      => 3637,
		"symbol"    => "ER_NOT_HINT_UPDATABLE_VARIABLE",
		"sql_state" => "HY000",
		"template"  => "Variable {#p1} cannot be set using SET_VAR hint.",
	],
	[
		"code"      => 3638,
		"symbol"    => "ER_CREDENTIALS_CONTRADICT_TO_HISTORY",
		"sql_state" => "HY000",
		"template"  => "Cannot use these credentials for '{#p1}@{#p2}' because they contradict the password history policy",
	],
	[
		"code"      => 3639,
		"symbol"    => "ER_WARNING_PASSWORD_HISTORY_CLAUSES_VOID",
		"sql_state" => "HY000",
		"template"  => "Non-zero password history clauses ignored for user '{#p1}'@'{#p2}' as its authentication plugin {#p3} does not support password history",
	],
	[
		"code"      => 3640,
		"symbol"    => "ER_CLIENT_DOES_NOT_SUPPORT",
		"sql_state" => "HY000",
		"template"  => "The client doesn't support {#p1}",
	],
	[
		"code"      => 3641,
		"symbol"    => "ER_I_S_SKIPPED_TABLESPACE",
		"sql_state" => "HY000",
		"template"  => "Tablespace '{#p1}' was skipped since its definition is being modified by concurrent DDL statement",
	],
	[
		"code"      => 3642,
		"symbol"    => "ER_TABLESPACE_ENGINE_MISMATCH",
		"sql_state" => "HY000",
		"template"  => "Engine '{#p1}' does not match stored engine '{#p2}' for tablespace '{#p3}'",
	],
	[
		"code"      => 3643,
		"symbol"    => "ER_WRONG_SRID_FOR_COLUMN",
		"sql_state" => "HY000",
		"template"  => "The SRID of the geometry does not match the SRID of the column '{#p1}'. The SRID of the geometry is {p2}, but the SRID of the column is {p3}. Consider changing the SRID of the geometry or the SRID property of the column.",
	],
	[
		"code"      => 3644,
		"symbol"    => "ER_CANNOT_ALTER_SRID_DUE_TO_INDEX",
		"sql_state" => "HY000",
		"template"  => "The SRID specification on the column '{#p1}' cannot be changed because there is a spatial index on the column. Please remove the spatial index before altering the SRID specification.",
	],
	[
		"code"      => 3645,
		"symbol"    => "ER_WARN_BINLOG_PARTIAL_UPDATES_DISABLED",
		"sql_state" => "HY000",
		"template"  => "When {#p1}, the option binlog_row_value_options={#p2} will be ignored and updates will be written in full format to binary log.",
	],
	[
		"code"      => 3646,
		"symbol"    => "ER_WARN_BINLOG_V1_ROW_EVENTS_DISABLED",
		"sql_state" => "HY000",
		"template"  => "When {#p1}, the option log_bin_use_v1_row_events=1 will be ignored and row events will be written in new format to binary log.",
	],
	[
		"code"      => 3647,
		"symbol"    => "ER_WARN_BINLOG_PARTIAL_UPDATES_SUGGESTS_PARTIAL_IMAGES",
		"sql_state" => "HY000",
		"template"  => "When {#p1}, the option binlog_row_value_options={#p2} will be used only for the after-image. Full values will be written in the before-image, so the saving in disk space due to binlog_row_value_options is limited to less than 50%%.",
	],
	[
		"code"      => 3648,
		"symbol"    => "ER_COULD_NOT_APPLY_JSON_DIFF",
		"sql_state" => "HY000",
		"template"  => "Could not apply JSON diff in table {#p1}, column {#p2}.",
	],
	[
		"code"      => 3649,
		"symbol"    => "ER_CORRUPTED_JSON_DIFF",
		"sql_state" => "HY000",
		"template"  => "Corrupted JSON diff for table {#p1}, column {#p2}.",
	],
	[
		"code"      => 3650,
		"symbol"    => "ER_RESOURCE_GROUP_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Resource Group '{#p1}' exists",
	],
	[
		"code"      => 3651,
		"symbol"    => "ER_RESOURCE_GROUP_NOT_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Resource Group '{#p1}' does not exist.",
	],
	[
		"code"      => 3652,
		"symbol"    => "ER_INVALID_VCPU_ID",
		"sql_state" => "HY000",
		"template"  => "Invalid cpu id {p1}",
	],
	[
		"code"      => 3653,
		"symbol"    => "ER_INVALID_VCPU_RANGE",
		"sql_state" => "HY000",
		"template"  => "Invalid VCPU range {p1}-{p2}",
	],
	[
		"code"      => 3654,
		"symbol"    => "ER_INVALID_THREAD_PRIORITY",
		"sql_state" => "HY000",
		"template"  => "Invalid thread priority value {p1} for {#p2} resource group {#p3}. Allowed range is [{p4}, {p5}].",
	],
	[
		"code"      => 3656,
		"symbol"    => "ER_RESOURCE_GROUP_BUSY",
		"sql_state" => "HY000",
		"template"  => "Resource group {#p1} is busy.",
	],
	[
		"code"      => 3657,
		"symbol"    => "ER_RESOURCE_GROUP_DISABLED",
		"sql_state" => "HY000",
		"template"  => "Resource group {#p1} is disabled.",
	],
	[
		"code"      => 3658,
		"symbol"    => "ER_FEATURE_UNSUPPORTED",
		"sql_state" => "HY000",
		"template"  => "Feature {#p1} is unsupported ({#p2}).",
	],
	[
		"code"      => 3659,
		"symbol"    => "ER_ATTRIBUTE_IGNORED",
		"sql_state" => "HY000",
		"template"  => "Attribute {#p1} is ignored ({#p2}).",
	],
	[
		"code"      => 3660,
		"symbol"    => "ER_INVALID_THREAD_ID",
		"sql_state" => "HY000",
		"template"  => "Invalid thread id ({p1}).",
	],
	[
		"code"      => 3661,
		"symbol"    => "ER_RESOURCE_GROUP_BIND_FAILED",
		"sql_state" => "HY000",
		"template"  => "Unable to bind resource group {#p1} with thread id ({p2}).({#p3}).",
	],
	[
		"code"      => 3662,
		"symbol"    => "ER_INVALID_USE_OF_FORCE_OPTION",
		"sql_state" => "HY000",
		"template"  => "Option FORCE invalid as DISABLE option is not specified.",
	],
	[
		"code"      => 3663,
		"symbol"    => "ER_GROUP_REPLICATION_COMMAND_FAILURE",
		"sql_state" => "HY000",
		"template"  => "The {#p1} command encountered a failure. {#p2}",
	],
	[
		"code"      => 3664,
		"symbol"    => "ER_SDI_OPERATION_FAILED",
		"sql_state" => "HY000",
		"template"  => "Failed to {#p1} SDI '{#p2}.{#p3}' in tablespace '{#p4}'.",
	],
	[
		"code"      => 3665,
		"symbol"    => "ER_MISSING_JSON_TABLE_VALUE",
		"sql_state" => "22035",
		"template"  => "Missing value for JSON_TABLE column '{#p1}'",
	],
	[
		"code"      => 3666,
		"symbol"    => "ER_WRONG_JSON_TABLE_VALUE",
		"sql_state" => "2203F",
		"template"  => "Can't store an array or an object in the scalar JSON_TABLE column '{#p1}'",
	],
	[
		"code"      => 3667,
		"symbol"    => "ER_TF_MUST_HAVE_ALIAS",
		"sql_state" => "42000",
		"template"  => "Every table function must have an alias",
	],
	[
		"code"      => 3668,
		"symbol"    => "ER_TF_FORBIDDEN_JOIN_TYPE",
		"sql_state" => "HY000",
		"template"  => "INNER or LEFT JOIN must be used for LATERAL references made by '{#p1}'",
	],
	[
		"code"      => 3669,
		"symbol"    => "ER_JT_VALUE_OUT_OF_RANGE",
		"sql_state" => "22003",
		"template"  => "Value is out of range for JSON_TABLE's column '{#p1}'",
	],
	[
		"code"      => 3670,
		"symbol"    => "ER_JT_MAX_NESTED_PATH",
		"sql_state" => "42000",
		"template"  => "More than supported {p1} NESTED PATHs were found in JSON_TABLE '{#p2}'",
	],
	[
		"code"      => 3671,
		"symbol"    => "ER_PASSWORD_EXPIRATION_NOT_SUPPORTED_BY_AUTH_METHOD",
		"sql_state" => "HY000",
		"template"  => "The selected authentication method {#p1} does not support password expiration",
	],
	[
		"code"      => 3672,
		"symbol"    => "ER_INVALID_GEOJSON_CRS_NOT_TOP_LEVEL",
		"sql_state" => "HY000",
		"template"  => "Invalid GeoJSON data provided to function {#p1}: Member 'crs' must be specified in the top level object.",
	],
	[
		"code"      => 3674,
		"symbol"    => "WARN_USELESS_SPATIAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "The spatial index on column '{#p1}' will not be used by the query optimizer since the column does not have an SRID attribute. Consider adding an SRID attribute to the column.",
	],
	[
		"code"      => 3675,
		"symbol"    => "ER_DISK_FULL_NOWAIT",
		"sql_state" => "HY000",
		"template"  => "Create table/tablespace '{#p1}' failed, as disk is full",
	],
	[
		"code"      => 3676,
		"symbol"    => "ER_PARSE_ERROR_IN_DIGEST_FN",
		"sql_state" => "HY000",
		"template"  => "Could not parse argument to digest function: \"{#p1}\".",
	],
	[
		"code"      => 3677,
		"symbol"    => "ER_UNDISCLOSED_PARSE_ERROR_IN_DIGEST_FN",
		"sql_state" => "HY000",
		"template"  => "Could not parse argument to digest function.",
	],
	[
		"code"      => 3678,
		"symbol"    => "ER_SCHEMA_DIR_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Schema directory '{#p1}' already exists. This must be resolved manually (e.g. by moving the schema directory to another location).",
	],
	[
		"code"      => 3679,
		"symbol"    => "ER_SCHEMA_DIR_MISSING",
		"sql_state" => "HY000",
		"template"  => "Schema directory '{#p1}' does not exist",
	],
	[
		"code"      => 3680,
		"symbol"    => "ER_SCHEMA_DIR_CREATE_FAILED",
		"sql_state" => "HY000",
		"template"  => "Failed to create schema directory '{#p1}' (errno: {p2} - {#p3})",
	],
	[
		"code"      => 3681,
		"symbol"    => "ER_SCHEMA_DIR_UNKNOWN",
		"sql_state" => "HY000",
		"template"  => "Schema '{#p1}' does not exist, but schema directory '{#p2}' was found. This must be resolved manually (e.g. by moving the schema directory to another location).",
	],
	[
		"code"      => 3682,
		"symbol"    => "ER_ONLY_IMPLEMENTED_FOR_SRID_0_AND_4326",
		"sql_state" => "22S00",
		"template"  => "Function {#p1} is only defined for SRID 0 and SRID 4326.",
	],
	[
		"code"      => 3683,
		"symbol"    => "ER_BINLOG_EXPIRE_LOG_DAYS_AND_SECS_USED_TOGETHER",
		"sql_state" => "HY000",
		"template"  => "The option expire_logs_days and binlog_expire_logs_seconds cannot be used together. Please use binlog_expire_logs_seconds to set the expire time (expire_logs_days is deprecated)",
	],
	[
		"code"      => 3684,
		"symbol"    => "ER_REGEXP_STRING_NOT_TERMINATED",
		"sql_state" => "HY000",
		"template"  => "An output string could not be zero-terminated because the length exceeds the buffer capacity.",
	],
	[
		"code"      => 3684,
		"symbol"    => "ER_REGEXP_BUFFER_OVERFLOW",
		"sql_state" => "HY000",
		"template"  => "The result string is larger than the result buffer.",
	],
	[
		"code"      => 3685,
		"symbol"    => "ER_REGEXP_ILLEGAL_ARGUMENT",
		"sql_state" => "HY000",
		"template"  => "Illegal argument to a regular expression.",
	],
	[
		"code"      => 3686,
		"symbol"    => "ER_REGEXP_INDEX_OUTOFBOUNDS_ERROR",
		"sql_state" => "HY000",
		"template"  => "Index out of bounds in regular expression search.",
	],
	[
		"code"      => 3687,
		"symbol"    => "ER_REGEXP_INTERNAL_ERROR",
		"sql_state" => "HY000",
		"template"  => "Internal error in the regular expression library.",
	],
	[
		"code"      => 3688,
		"symbol"    => "ER_REGEXP_RULE_SYNTAX",
		"sql_state" => "HY000",
		"template"  => "Syntax error in regular expression on line {p1}, character {p2}.",
	],
	[
		"code"      => 3689,
		"symbol"    => "ER_REGEXP_BAD_ESCAPE_SEQUENCE",
		"sql_state" => "HY000",
		"template"  => "Unrecognized escape sequence in regular expression.",
	],
	[
		"code"      => 3690,
		"symbol"    => "ER_REGEXP_UNIMPLEMENTED",
		"sql_state" => "HY000",
		"template"  => "The regular expression contains a feature that is not implemented in this library version.",
	],
	[
		"code"      => 3691,
		"symbol"    => "ER_REGEXP_MISMATCHED_PAREN",
		"sql_state" => "HY000",
		"template"  => "Mismatched parenthesis in regular expression.",
	],
	[
		"code"      => 3692,
		"symbol"    => "ER_REGEXP_BAD_INTERVAL",
		"sql_state" => "HY000",
		"template"  => "Incorrect description of a {min,max} interval.",
	],
	[
		"code"      => 3693,
		"symbol"    => "ER_REGEXP_MAX_LT_MIN",
		"sql_state" => "HY000",
		"template"  => "The maximum is less than the minumum in a {min,max} interval.",
	],
	[
		"code"      => 3694,
		"symbol"    => "ER_REGEXP_INVALID_BACK_REF",
		"sql_state" => "HY000",
		"template"  => "Invalid back-reference in regular expression.",
	],
	[
		"code"      => 3695,
		"symbol"    => "ER_REGEXP_LOOK_BEHIND_LIMIT",
		"sql_state" => "HY000",
		"template"  => "The look-behind assertion exceeds the limit in regular expression.",
	],
	[
		"code"      => 3696,
		"symbol"    => "ER_REGEXP_MISSING_CLOSE_BRACKET",
		"sql_state" => "HY000",
		"template"  => "The regular expression contains an unclosed bracket expression.",
	],
	[
		"code"      => 3697,
		"symbol"    => "ER_REGEXP_INVALID_RANGE",
		"sql_state" => "HY000",
		"template"  => "The regular expression contains an [x-y] character range where x comes after y.",
	],
	[
		"code"      => 3698,
		"symbol"    => "ER_REGEXP_STACK_OVERFLOW",
		"sql_state" => "HY000",
		"template"  => "Overflow in the regular expression backtrack stack.",
	],
	[
		"code"      => 3699,
		"symbol"    => "ER_REGEXP_TIME_OUT",
		"sql_state" => "HY000",
		"template"  => "Timeout exceeded in regular expression match.",
	],
	[
		"code"      => 3700,
		"symbol"    => "ER_REGEXP_PATTERN_TOO_BIG",
		"sql_state" => "HY000",
		"template"  => "The regular expression pattern exceeds limits on size or complexity.",
	],
	[
		"code"      => 3701,
		"symbol"    => "ER_CANT_SET_ERROR_LOG_SERVICE",
		"sql_state" => "HY000",
		"template"  => "Value for {#p1} got confusing at or around \"{#p2}\". Syntax may be wrong, component may not be INSTALLed, or a component that does not support instances may be listed more than once.",
	],
	[
		"code"      => 3702,
		"symbol"    => "ER_EMPTY_PIPELINE_FOR_ERROR_LOG_SERVICE",
		"sql_state" => "HY000",
		"template"  => "Setting an empty {#p1} pipeline disables error logging!",
	],
	[
		"code"      => 3703,
		"symbol"    => "ER_COMPONENT_FILTER_DIAGNOSTICS",
		"sql_state" => "HY000",
		"template"  => "filter {#p1}: {#p2}",
	],
	[
		"code"      => 3704,
		"symbol"    => "ER_INNODB_CANNOT_BE_IGNORED",
		"sql_state" => "HY000",
		"template"  => "ignore-builtin-innodb is ignored and will be removed in future releases.",
	],
	[
		"code"      => 3704,
		"symbol"    => "ER_NOT_IMPLEMENTED_FOR_CARTESIAN_SRS",
		"sql_state" => "22S00",
		"template"  => "{#p1}({#p2}) has not been implemented for Cartesian spatial reference systems.",
	],
	[
		"code"      => 3705,
		"symbol"    => "ER_NOT_IMPLEMENTED_FOR_PROJECTED_SRS",
		"sql_state" => "22S00",
		"template"  => "{#p1}({#p2}) has not been implemented for projected spatial reference systems.",
	],
	[
		"code"      => 3706,
		"symbol"    => "ER_NONPOSITIVE_RADIUS",
		"sql_state" => "22003",
		"template"  => "Invalid radius provided to function {#p1}: Radius must be greater than zero.",
	],
	[
		"code"      => 3707,
		"symbol"    => "ER_RESTART_SERVER_FAILED",
		"sql_state" => "HY000",
		"template"  => "Restart server failed ({#p1}).",
	],
	[
		"code"      => 3708,
		"symbol"    => "ER_SRS_MISSING_MANDATORY_ATTRIBUTE",
		"sql_state" => "SR006",
		"template"  => "Missing mandatory attribute {#p1}.",
	],
	[
		"code"      => 3709,
		"symbol"    => "ER_SRS_MULTIPLE_ATTRIBUTE_DEFINITIONS",
		"sql_state" => "SR006",
		"template"  => "Multiple definitions of attribute {#p1}.",
	],
	[
		"code"      => 3710,
		"symbol"    => "ER_SRS_NAME_CANT_BE_EMPTY_OR_WHITESPACE",
		"sql_state" => "SR006",
		"template"  => "The spatial reference system name can't be an empty string or start or end with whitespace.",
	],
	[
		"code"      => 3711,
		"symbol"    => "ER_SRS_ORGANIZATION_CANT_BE_EMPTY_OR_WHITESPACE",
		"sql_state" => "SR006",
		"template"  => "The organization name can't be an empty string or start or end with whitespace.",
	],
	[
		"code"      => 3712,
		"symbol"    => "ER_SRS_ID_ALREADY_EXISTS",
		"sql_state" => "SR004",
		"template"  => "There is already a spatial reference system with SRID {p1}.",
	],
	[
		"code"      => 3713,
		"symbol"    => "ER_WARN_SRS_ID_ALREADY_EXISTS",
		"sql_state" => "01S00",
		"template"  => "There is already a spatial reference system with SRID {p1}.",
	],
	[
		"code"      => 3714,
		"symbol"    => "ER_CANT_MODIFY_SRID_0",
		"sql_state" => "SR000",
		"template"  => "SRID 0 is not modifiable.",
	],
	[
		"code"      => 3715,
		"symbol"    => "ER_WARN_RESERVED_SRID_RANGE",
		"sql_state" => "01S01",
		"template"  => "The SRID range [{p1}, {p2}] has been reserved for system use. SRSs in this range may be added, modified or removed without warning during upgrade.",
	],
	[
		"code"      => 3716,
		"symbol"    => "ER_CANT_MODIFY_SRS_USED_BY_COLUMN",
		"sql_state" => "SR005",
		"template"  => "Can't modify SRID {p1}. There is at least one column depending on it.",
	],
	[
		"code"      => 3717,
		"symbol"    => "ER_SRS_INVALID_CHARACTER_IN_ATTRIBUTE",
		"sql_state" => "SR006",
		"template"  => "Invalid character in attribute {#p1}.",
	],
	[
		"code"      => 3718,
		"symbol"    => "ER_SRS_ATTRIBUTE_STRING_TOO_LONG",
		"sql_state" => "SR006",
		"template"  => "Attribute {#p1} is too long. The maximum length is {p2} characters.",
	],
	[
		"code"      => 3719,
		"symbol"    => "ER_DEPRECATED_UTF8_ALIAS",
		"sql_state" => "HY000",
		"template"  => "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.",
	],
	[
		"code"      => 3720,
		"symbol"    => "ER_DEPRECATED_NATIONAL",
		"sql_state" => "HY000",
		"template"  => "NATIONAL/NCHAR/NVARCHAR implies the character set UTF8MB3, which will be replaced by UTF8MB4 in a future release. Please consider using CHAR(x) CHARACTER SET UTF8MB4 in order to be unambiguous.",
	],
	[
		"code"      => 3721,
		"symbol"    => "ER_INVALID_DEFAULT_UTF8MB4_COLLATION",
		"sql_state" => "HY000",
		"template"  => "Invalid default collation {#p1}: utf8mb4_0900_ai_ci or utf8mb4_general_ci expected",
	],
	[
		"code"      => 3722,
		"symbol"    => "ER_UNABLE_TO_COLLECT_LOG_STATUS",
		"sql_state" => "HY000",
		"template"  => "Unable to collect information for column '{#p1}': {#p2}.",
	],
	[
		"code"      => 3723,
		"symbol"    => "ER_RESERVED_TABLESPACE_NAME",
		"sql_state" => "HY000",
		"template"  => "The table '{#p1}' may not be created in the reserved tablespace '{#p2}'.",
	],
	[
		"code"      => 3724,
		"symbol"    => "ER_UNABLE_TO_SET_OPTION",
		"sql_state" => "HY000",
		"template"  => "This option cannot be set {#p1}.",
	],
	[
		"code"      => 3725,
		"symbol"    => "ER_SLAVE_POSSIBLY_DIVERGED_AFTER_DDL",
		"sql_state" => "HY000",
		"template"  => "A commit for an atomic DDL statement was unsuccessful on the master and the slave. The slave supports atomic DDL statements but the master does not, so the action taken by the slave and master might differ. Check that their states have not diverged before proceeding.",
	],
	[
		"code"      => 3726,
		"symbol"    => "ER_SRS_NOT_GEOGRAPHIC",
		"sql_state" => "22S00",
		"template"  => "Function {#p1} is only defined for geographic spatial reference systems, but one of its arguments is in SRID {p2}, which is not geographic.",
	],
	[
		"code"      => 3727,
		"symbol"    => "ER_POLYGON_TOO_LARGE",
		"sql_state" => "22023",
		"template"  => "Function {#p1} encountered a polygon that was too large. Polygons must cover less than half the planet.",
	],
	[
		"code"      => 3728,
		"symbol"    => "ER_SPATIAL_UNIQUE_INDEX",
		"sql_state" => "HY000",
		"template"  => "Spatial indexes can't be primary or unique indexes.",
	],
	[
		"code"      => 3729,
		"symbol"    => "ER_INDEX_TYPE_NOT_SUPPORTED_FOR_SPATIAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "The index type {#p1} is not supported for spatial indexes.",
	],
	[
		"code"      => 3730,
		"symbol"    => "ER_FK_CANNOT_DROP_PARENT",
		"sql_state" => "HY000",
		"template"  => "Cannot drop table '{#p1}' referenced by a foreign key constraint '{#p2}' on table '{#p3}'.",
	],
	[
		"code"      => 3731,
		"symbol"    => "ER_GEOMETRY_PARAM_LONGITUDE_OUT_OF_RANGE",
		"sql_state" => "22S02",
		"template"  => "A parameter of function {#p1} contains a geometry with longitude {p2}, which is out of range. It must be within ({p3}, {p4}].",
	],
	[
		"code"      => 3732,
		"symbol"    => "ER_GEOMETRY_PARAM_LATITUDE_OUT_OF_RANGE",
		"sql_state" => "22S03",
		"template"  => "A parameter of function {#p1} contains a geometry with latitude {p2}, which is out of range. It must be within [{p3}, {p4}].",
	],
	[
		"code"      => 3733,
		"symbol"    => "ER_FK_CANNOT_USE_VIRTUAL_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Foreign key '{#p1}' uses virtual column '{#p2}' which is not supported.",
	],
	[
		"code"      => 3734,
		"symbol"    => "ER_FK_NO_COLUMN_PARENT",
		"sql_state" => "HY000",
		"template"  => "Failed to add the foreign key constraint. Missing column '{#p1}' for constraint '{#p2}' in the referenced table '{#p3}'",
	],
	[
		"code"      => 3735,
		"symbol"    => "ER_CANT_SET_ERROR_SUPPRESSION_LIST",
		"sql_state" => "HY000",
		"template"  => "{#p1}: Could not add suppression rule for code \"{#p2}\". Rule-set may be full, or code may not correspond to an error-log message.",
	],
	[
		"code"      => 3736,
		"symbol"    => "ER_SRS_GEOGCS_INVALID_AXES",
		"sql_state" => "SR002",
		"template"  => "The spatial reference system definition for SRID {p1} specifies invalid geographic axes '{#p2}' and '{#p3}'. One axis must be NORTH or SOUTH and the other must be EAST or WEST.",
	],
	[
		"code"      => 3737,
		"symbol"    => "ER_SRS_INVALID_SEMI_MAJOR_AXIS",
		"sql_state" => "SR002",
		"template"  => "The length of the semi-major axis must be a positive number.",
	],
	[
		"code"      => 3738,
		"symbol"    => "ER_SRS_INVALID_INVERSE_FLATTENING",
		"sql_state" => "SR002",
		"template"  => "The inverse flattening must be larger than 1.0, or 0.0 if the ellipsoid is a sphere.",
	],
	[
		"code"      => 3739,
		"symbol"    => "ER_SRS_INVALID_ANGULAR_UNIT",
		"sql_state" => "SR002",
		"template"  => "The angular unit conversion factor must be a positive number.",
	],
	[
		"code"      => 3740,
		"symbol"    => "ER_SRS_INVALID_PRIME_MERIDIAN",
		"sql_state" => "SR002",
		"template"  => "The prime meridian must be within (-180, 180] degrees, specified in the SRS angular unit.",
	],
	[
		"code"      => 3741,
		"symbol"    => "ER_TRANSFORM_SOURCE_SRS_NOT_SUPPORTED",
		"sql_state" => "22S00",
		"template"  => "Transformation from SRID {p1} is not supported.",
	],
	[
		"code"      => 3742,
		"symbol"    => "ER_TRANSFORM_TARGET_SRS_NOT_SUPPORTED",
		"sql_state" => "22S00",
		"template"  => "Transformation to SRID {p1} is not supported.",
	],
	[
		"code"      => 3743,
		"symbol"    => "ER_TRANSFORM_SOURCE_SRS_MISSING_TOWGS84",
		"sql_state" => "22S00",
		"template"  => "Transformation from SRID {p1} is not supported. The spatial reference system has no TOWGS84 clause.",
	],
	[
		"code"      => 3744,
		"symbol"    => "ER_TRANSFORM_TARGET_SRS_MISSING_TOWGS84",
		"sql_state" => "22S00",
		"template"  => "Transformation to SRID {p1} is not supported. The spatial reference system has no TOWGS84 clause.",
	],
	[
		"code"      => 3745,
		"symbol"    => "ER_TEMP_TABLE_PREVENTS_SWITCH_SESSION_BINLOG_FORMAT",
		"sql_state" => "HY000",
		"template"  => "Changing @@session.binlog_format is disallowed when the session has open temporary table(s). You could wait until these temporary table(s) are dropped and try again.",
	],
	[
		"code"      => 3746,
		"symbol"    => "ER_TEMP_TABLE_PREVENTS_SWITCH_GLOBAL_BINLOG_FORMAT",
		"sql_state" => "HY000",
		"template"  => "Changing @@global.binlog_format or @@persist.binlog_format is disallowed when any replication channel has open temporary table(s). You could wait until Slave_open_temp_tables = 0 and try again",
	],
	[
		"code"      => 3747,
		"symbol"    => "ER_RUNNING_APPLIER_PREVENTS_SWITCH_GLOBAL_BINLOG_FORMAT",
		"sql_state" => "HY000",
		"template"  => "Changing @@global.binlog_format or @@persist.binlog_format is disallowed when any replication channel applier thread is running. You could execute STOP SLAVE SQL_THREAD and try again.",
	],
	[
		"code"      => 3748,
		"symbol"    => "ER_CLIENT_GTID_UNSAFE_CREATE_DROP_TEMP_TABLE_IN_TRX_IN_SBR",
		"sql_state" => "HY000",
		"template"  => "Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE are not allowed inside a transaction or inside a procedure in a transactional context when @@session.binlog_format=STATEMENT.",
	],
	[
		"code"      => 3750,
		"symbol"    => "ER_TABLE_WITHOUT_PK",
		"sql_state" => "HY000",
		"template"  => "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.",
	],
	[
		"code"      => 3751,
		"symbol"    => "WARN_DATA_TRUNCATED_FUNCTIONAL_INDEX",
		"sql_state" => "01000",
		"template"  => "Data truncated for functional index '{#p1}' at row {p2}",
	],
	[
		"code"      => 3751,
		"symbol"    => "ER_WARN_DATA_TRUNCATED_FUNCTIONAL_INDEX",
		"sql_state" => "01000",
		"template"  => "Data truncated for functional index '{#p1}' at row {p2}",
	],
	[
		"code"      => 3752,
		"symbol"    => "ER_WARN_DATA_OUT_OF_RANGE_FUNCTIONAL_INDEX",
		"sql_state" => "22003",
		"template"  => "Value is out of range for functional index '{#p1}' at row {p2}",
	],
	[
		"code"      => 3753,
		"symbol"    => "ER_FUNCTIONAL_INDEX_ON_JSON_OR_GEOMETRY_FUNCTION",
		"sql_state" => "42000",
		"template"  => "Cannot create a functional index on a function that returns a JSON or GEOMETRY value.",
	],
	[
		"code"      => 3754,
		"symbol"    => "ER_FUNCTIONAL_INDEX_REF_AUTO_INCREMENT",
		"sql_state" => "HY000",
		"template"  => "Functional index '{#p1}' cannot refer to an auto-increment column.",
	],
	[
		"code"      => 3755,
		"symbol"    => "ER_CANNOT_DROP_COLUMN_FUNCTIONAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "Cannot drop column '{#p1}' because it is used by a functional index. In order to drop the column, you must remove the functional index.",
	],
	[
		"code"      => 3756,
		"symbol"    => "ER_FUNCTIONAL_INDEX_PRIMARY_KEY",
		"sql_state" => "HY000",
		"template"  => "The primary key cannot be a functional index",
	],
	[
		"code"      => 3757,
		"symbol"    => "ER_FUNCTIONAL_INDEX_ON_LOB",
		"sql_state" => "HY000",
		"template"  => "Cannot create a functional index on an expression that returns a BLOB or TEXT. Please consider using CAST.",
	],
	[
		"code"      => 3758,
		"symbol"    => "ER_FUNCTIONAL_INDEX_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "Expression of functional index '{#p1}' contains a disallowed function.",
	],
	[
		"code"      => 3759,
		"symbol"    => "ER_FULLTEXT_FUNCTIONAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "Fulltext functional index is not supported.",
	],
	[
		"code"      => 3760,
		"symbol"    => "ER_SPATIAL_FUNCTIONAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "Spatial functional index is not supported.",
	],
	[
		"code"      => 3761,
		"symbol"    => "ER_WRONG_KEY_COLUMN_FUNCTIONAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "The used storage engine cannot index the expression '{#p1}'.",
	],
	[
		"code"      => 3762,
		"symbol"    => "ER_FUNCTIONAL_INDEX_ON_FIELD",
		"sql_state" => "HY000",
		"template"  => "Functional index on a column is not supported. Consider using a regular index instead.",
	],
	[
		"code"      => 3763,
		"symbol"    => "ER_GENERATED_COLUMN_NAMED_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "Expression of generated column '{#p1}' contains a disallowed function: {#p2}.",
	],
	[
		"code"      => 3764,
		"symbol"    => "ER_GENERATED_COLUMN_ROW_VALUE",
		"sql_state" => "HY000",
		"template"  => "Expression of generated column '{#p1}' cannot refer to a row value.",
	],
	[
		"code"      => 3765,
		"symbol"    => "ER_GENERATED_COLUMN_VARIABLES",
		"sql_state" => "HY000",
		"template"  => "Expression of generated column '{#p1}' cannot refer user or system variables.",
	],
	[
		"code"      => 3766,
		"symbol"    => "ER_DEPENDENT_BY_DEFAULT_GENERATED_VALUE",
		"sql_state" => "HY000",
		"template"  => "Column '{#p1}' of table '{#p2}' has a default value expression dependency and cannot be dropped or renamed.",
	],
	[
		"code"      => 3767,
		"symbol"    => "ER_DEFAULT_VAL_GENERATED_NON_PRIOR",
		"sql_state" => "HY000",
		"template"  => "Default value expression of column '{#p1}' cannot refer to a column defined after it if that column is a generated column or has an expression as default value.",
	],
	[
		"code"      => 3768,
		"symbol"    => "ER_DEFAULT_VAL_GENERATED_REF_AUTO_INC",
		"sql_state" => "HY000",
		"template"  => "Default value expression of column '{#p1}' cannot refer to an auto-increment column.",
	],
	[
		"code"      => 3769,
		"symbol"    => "ER_DEFAULT_VAL_GENERATED_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "Default value expression of column '{#p1}' contains a disallowed function.",
	],
	[
		"code"      => 3770,
		"symbol"    => "ER_DEFAULT_VAL_GENERATED_NAMED_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "Default value expression of column '{#p1}' contains a disallowed function: {#p2}.",
	],
	[
		"code"      => 3771,
		"symbol"    => "ER_DEFAULT_VAL_GENERATED_ROW_VALUE",
		"sql_state" => "HY000",
		"template"  => "Default value expression of column '{#p1}' cannot refer to a row value.",
	],
	[
		"code"      => 3772,
		"symbol"    => "ER_DEFAULT_VAL_GENERATED_VARIABLES",
		"sql_state" => "HY000",
		"template"  => "Default value expression of column '{#p1}' cannot refer user or system variables.",
	],
	[
		"code"      => 3773,
		"symbol"    => "ER_DEFAULT_AS_VAL_GENERATED",
		"sql_state" => "HY000",
		"template"  => "DEFAULT function cannot be used with default value expressions",
	],
	[
		"code"      => 3774,
		"symbol"    => "ER_UNSUPPORTED_ACTION_ON_DEFAULT_VAL_GENERATED",
		"sql_state" => "HY000",
		"template"  => "'{#p1}' is not supported for default value expressions.",
	],
	[
		"code"      => 3775,
		"symbol"    => "ER_GTID_UNSAFE_ALTER_ADD_COL_WITH_DEFAULT_EXPRESSION",
		"sql_state" => "HY000",
		"template"  => "Statement violates GTID consistency: ALTER TABLE ... ADD COLUMN .. with expression as DEFAULT.",
	],
	[
		"code"      => 3776,
		"symbol"    => "ER_FK_CANNOT_CHANGE_ENGINE",
		"sql_state" => "HY000",
		"template"  => "Cannot change table's storage engine because the table participates in a foreign key constraint.",
	],
	[
		"code"      => 3777,
		"symbol"    => "ER_WARN_DEPRECATED_USER_SET_EXPR",
		"sql_state" => "HY000",
		"template"  => "Setting user variables within expressions is deprecated and will be removed in a future release. Consider alternatives: 'SET variable=expression, ...', or 'SELECT expression(s) INTO variables(s)'.",
	],
	[
		"code"      => 3778,
		"symbol"    => "ER_WARN_DEPRECATED_UTF8MB3_COLLATION",
		"sql_state" => "HY000",
		"template"  => "'{#p1}' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.",
	],
	[
		"code"      => 3779,
		"symbol"    => "ER_WARN_DEPRECATED_NESTED_COMMENT_SYNTAX",
		"sql_state" => "HY000",
		"template"  => "Nested comment syntax is deprecated and will be removed in a future release.",
	],
	[
		"code"      => 3780,
		"symbol"    => "ER_FK_INCOMPATIBLE_COLUMNS",
		"sql_state" => "HY000",
		"template"  => "Referencing column '{#p1}' and referenced column '{#p2}' in foreign key constraint '{#p3}' are incompatible.",
	],
	[
		"code"      => 3781,
		"symbol"    => "ER_GR_HOLD_WAIT_TIMEOUT",
		"sql_state" => "HY000",
		"template"  => "Timeout exceeded for held statement while new Group Replication primary member is applying backlog.",
	],
	[
		"code"      => 3782,
		"symbol"    => "ER_GR_HOLD_KILLED",
		"sql_state" => "HY000",
		"template"  => "Held statement aborted because Group Replication plugin got shut down or thread was killed while new primary member was applying backlog.",
	],
	[
		"code"      => 3783,
		"symbol"    => "ER_GR_HOLD_MEMBER_STATUS_ERROR",
		"sql_state" => "HY000",
		"template"  => "Held statement was aborted due to member being in error state, while backlog is being applied during Group Replication primary election.",
	],
	[
		"code"      => 3784,
		"symbol"    => "ER_RPL_ENCRYPTION_FAILED_TO_FETCH_KEY",
		"sql_state" => "HY000",
		"template"  => "Failed to fetch key from keyring, please check if keyring plugin is loaded.",
	],
	[
		"code"      => 3785,
		"symbol"    => "ER_RPL_ENCRYPTION_KEY_NOT_FOUND",
		"sql_state" => "HY000",
		"template"  => "Can't find key from keyring, please check in the server log if a keyring plugin is loaded and initialized successfully.",
	],
	[
		"code"      => 3786,
		"symbol"    => "ER_RPL_ENCRYPTION_KEYRING_INVALID_KEY",
		"sql_state" => "HY000",
		"template"  => "Fetched an invalid key from keyring.",
	],
	[
		"code"      => 3787,
		"symbol"    => "ER_RPL_ENCRYPTION_HEADER_ERROR",
		"sql_state" => "HY000",
		"template"  => "Error reading a replication log encryption header: {#p1}.",
	],
	[
		"code"      => 3788,
		"symbol"    => "ER_RPL_ENCRYPTION_FAILED_TO_ROTATE_LOGS",
		"sql_state" => "HY000",
		"template"  => "Failed to rotate some logs after changing binlog encryption settings. Please fix the problem and rotate the logs manually.",
	],
	[
		"code"      => 3789,
		"symbol"    => "ER_RPL_ENCRYPTION_KEY_EXISTS_UNEXPECTED",
		"sql_state" => "HY000",
		"template"  => "Key {#p1} exists unexpected.",
	],
	[
		"code"      => 3790,
		"symbol"    => "ER_RPL_ENCRYPTION_FAILED_TO_GENERATE_KEY",
		"sql_state" => "HY000",
		"template"  => "Failed to generate key, please check if keyring plugin is loaded.",
	],
	[
		"code"      => 3791,
		"symbol"    => "ER_RPL_ENCRYPTION_FAILED_TO_STORE_KEY",
		"sql_state" => "HY000",
		"template"  => "Failed to store key, please check if keyring plugin is loaded.",
	],
	[
		"code"      => 3792,
		"symbol"    => "ER_RPL_ENCRYPTION_FAILED_TO_REMOVE_KEY",
		"sql_state" => "HY000",
		"template"  => "Failed to remove key, please check if keyring plugin is loaded.",
	],
	[
		"code"      => 3793,
		"symbol"    => "ER_RPL_ENCRYPTION_UNABLE_TO_CHANGE_OPTION",
		"sql_state" => "HY000",
		"template"  => "Failed to change binlog_encryption value. {#p1}.",
	],
	[
		"code"      => 3794,
		"symbol"    => "ER_RPL_ENCRYPTION_MASTER_KEY_RECOVERY_FAILED",
		"sql_state" => "HY000",
		"template"  => "Unable to recover binlog encryption master key, please check if keyring plugin is loaded.",
	],
	[
		"code"      => 3795,
		"symbol"    => "ER_SLOW_LOG_MODE_IGNORED_WHEN_NOT_LOGGING_TO_FILE",
		"sql_state" => "HY000",
		"template"  => "slow query log file format changed as requested, but setting will have no effect when not actually logging to a file.",
	],
	[
		"code"      => 3796,
		"symbol"    => "ER_GRP_TRX_CONSISTENCY_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "The option group_replication_consistency cannot be used on the current member state.",
	],
	[
		"code"      => 3797,
		"symbol"    => "ER_GRP_TRX_CONSISTENCY_BEFORE",
		"sql_state" => "HY000",
		"template"  => "Error while waiting for group transactions commit on group_replication_consistency= 'BEFORE'.",
	],
	[
		"code"      => 3798,
		"symbol"    => "ER_GRP_TRX_CONSISTENCY_AFTER_ON_TRX_BEGIN",
		"sql_state" => "HY000",
		"template"  => "Error while waiting for transactions with group_replication_consistency= 'AFTER' to commit.",
	],
	[
		"code"      => 3799,
		"symbol"    => "ER_GRP_TRX_CONSISTENCY_BEGIN_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "The Group Replication plugin is stopping, therefore new transactions are not allowed to start.",
	],
	[
		"code"      => 3800,
		"symbol"    => "ER_FUNCTIONAL_INDEX_ROW_VALUE_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "Expression of functional index '{#p1}' cannot refer to a row value.",
	],
	[
		"code"      => 3801,
		"symbol"    => "ER_RPL_ENCRYPTION_FAILED_TO_ENCRYPT",
		"sql_state" => "HY000",
		"template"  => "Failed to encrypt content to write into binlog file: {#p1}.",
	],
	[
		"code"      => 3802,
		"symbol"    => "ER_PAGE_TRACKING_NOT_STARTED",
		"sql_state" => "HY000",
		"template"  => "Page Tracking is not started yet.",
	],
	[
		"code"      => 3803,
		"symbol"    => "ER_PAGE_TRACKING_RANGE_NOT_TRACKED",
		"sql_state" => "HY000",
		"template"  => "Tracking was not enabled for the LSN range specified",
	],
	[
		"code"      => 3804,
		"symbol"    => "ER_PAGE_TRACKING_CANNOT_PURGE",
		"sql_state" => "HY000",
		"template"  => "Cannot purge data when concurrent clone is in progress. Try later.",
	],
	[
		"code"      => 3805,
		"symbol"    => "ER_RPL_ENCRYPTION_CANNOT_ROTATE_BINLOG_MASTER_KEY",
		"sql_state" => "HY000",
		"template"  => "Cannot rotate binary log master key when 'binlog-encryption' is off.",
	],
	[
		"code"      => 3806,
		"symbol"    => "ER_BINLOG_MASTER_KEY_RECOVERY_OUT_OF_COMBINATION",
		"sql_state" => "HY000",
		"template"  => "Unable to recover binary log master key, the combination of new_master_key_seqno={p1}, master_key_seqno={p2} and old_master_key_seqno={p3} are wrong.",
	],
	[
		"code"      => 3807,
		"symbol"    => "ER_BINLOG_MASTER_KEY_ROTATION_FAIL_TO_OPERATE_KEY",
		"sql_state" => "HY000",
		"template"  => "Failed to operate binary log master key on keyring, please check if keyring plugin is loaded. The statement had no effect: the old binary log master key is still in use, the keyring, binary and relay log files are unchanged, and the server could not start using a new binary log master key for encrypting new binary and relay log files.",
	],
	[
		"code"      => 3808,
		"symbol"    => "ER_BINLOG_MASTER_KEY_ROTATION_FAIL_TO_ROTATE_LOGS",
		"sql_state" => "HY000",
		"template"  => "Failed to rotate one or more binary or relay log files. A new binary log master key was generated and will be used to encrypt new binary and relay log files. There may still exist binary or relay log files using the previous binary log master key.",
	],
	[
		"code"      => 3809,
		"symbol"    => "ER_BINLOG_MASTER_KEY_ROTATION_FAIL_TO_REENCRYPT_LOG",
		"sql_state" => "HY000",
		"template"  => "{#p1}. A new binary log master key was generated and will be used to encrypt new binary and relay log files. There may still exist binary or relay log files using the previous binary log master key.",
	],
	[
		"code"      => 3810,
		"symbol"    => "ER_BINLOG_MASTER_KEY_ROTATION_FAIL_TO_CLEANUP_UNUSED_KEYS",
		"sql_state" => "HY000",
		"template"  => "Failed to remove unused binary log encryption keys from the keyring, please check if keyring plugin is loaded. The unused binary log encryption keys may still exist in the keyring, and they will be removed upon server restart or next 'ALTER INSTANCE ROTATE BINLOG MASTER KEY' execution.",
	],
	[
		"code"      => 3811,
		"symbol"    => "ER_BINLOG_MASTER_KEY_ROTATION_FAIL_TO_CLEANUP_AUX_KEY",
		"sql_state" => "HY000",
		"template"  => "Failed to remove auxiliary binary log encryption key from keyring, please check if keyring plugin is loaded. The cleanup of the binary log master key rotation process did not finish as expected and the cleanup will take place upon server restart or next 'ALTER INSTANCE ROTATE BINLOG MASTER KEY' execution.",
	],
	[
		"code"      => 3812,
		"symbol"    => "ER_NON_BOOLEAN_EXPR_FOR_CHECK_CONSTRAINT",
		"sql_state" => "HY000",
		"template"  => "An expression of non-boolean type specified to a check constraint '{#p1}'.",
	],
	[
		"code"      => 3813,
		"symbol"    => "ER_COLUMN_CHECK_CONSTRAINT_REFERENCES_OTHER_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Column check constraint '{#p1}' references other column.",
	],
	[
		"code"      => 3814,
		"symbol"    => "ER_CHECK_CONSTRAINT_NAMED_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "An expression of a check constraint '{#p1}' contains disallowed function: {#p2}.",
	],
	[
		"code"      => 3815,
		"symbol"    => "ER_CHECK_CONSTRAINT_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "An expression of a check constraint '{#p1}' contains disallowed function.",
	],
	[
		"code"      => 3816,
		"symbol"    => "ER_CHECK_CONSTRAINT_VARIABLES",
		"sql_state" => "HY000",
		"template"  => "An expression of a check constraint '{#p1}' cannot refer to a user or system variable.",
	],
	[
		"code"      => 3817,
		"symbol"    => "ER_CHECK_CONSTRAINT_ROW_VALUE",
		"sql_state" => "HY000",
		"template"  => "Check constraint '{#p1}' cannot refer to a row value.",
	],
	[
		"code"      => 3818,
		"symbol"    => "ER_CHECK_CONSTRAINT_REFERS_AUTO_INCREMENT_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Check constraint '{#p1}' cannot refer to an auto-increment column.",
	],
	[
		"code"      => 3819,
		"symbol"    => "ER_CHECK_CONSTRAINT_VIOLATED",
		"sql_state" => "HY000",
		"template"  => "Check constraint '{#p1}' is violated.",
	],
	[
		"code"      => 3820,
		"symbol"    => "ER_CHECK_CONSTRAINT_REFERS_UNKNOWN_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Check constraint '{#p1}' refers to non-existing column '{#p2}'.",
	],
	[
		"code"      => 3821,
		"symbol"    => "ER_CHECK_CONSTRAINT_NOT_FOUND",
		"sql_state" => "HY000",
		"template"  => "Check constraint '{#p1}' is not found in the table.",
	],
	[
		"code"      => 3822,
		"symbol"    => "ER_CHECK_CONSTRAINT_DUP_NAME",
		"sql_state" => "HY000",
		"template"  => "Duplicate check constraint name '{#p1}'.",
	],
	[
		"code"      => 3823,
		"symbol"    => "ER_CHECK_CONSTRAINT_CLAUSE_USING_FK_REFER_ACTION_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Column '{#p1}' cannot be used in a check constraint '{#p2}': needed in a foreign key constraint '{#p3}' referential action.",
	],
	[
		"code"      => 3824,
		"symbol"    => "WARN_UNENCRYPTED_TABLE_IN_ENCRYPTED_DB",
		"sql_state" => "HY000",
		"template"  => "Creating an unencrypted table in a database with default encryption enabled.",
	],
	[
		"code"      => 3825,
		"symbol"    => "ER_INVALID_ENCRYPTION_REQUEST",
		"sql_state" => "HY000",
		"template"  => "Request to create {#p1} table while using an {#p2} tablespace.",
	],
	[
		"code"      => 3826,
		"symbol"    => "ER_CANNOT_SET_TABLE_ENCRYPTION",
		"sql_state" => "HY000",
		"template"  => "Table encryption differ from its database default encryption, and user doesn't have enough privilege.",
	],
	[
		"code"      => 3827,
		"symbol"    => "ER_CANNOT_SET_DATABASE_ENCRYPTION",
		"sql_state" => "HY000",
		"template"  => "Database default encryption differ from 'default_table_encryption' setting, and user doesn't have enough privilege.",
	],
	[
		"code"      => 3828,
		"symbol"    => "ER_CANNOT_SET_TABLESPACE_ENCRYPTION",
		"sql_state" => "HY000",
		"template"  => "Tablespace encryption differ from 'default_table_encryption' setting, and user doesn't have enough privilege.",
	],
	[
		"code"      => 3829,
		"symbol"    => "ER_TABLESPACE_CANNOT_BE_ENCRYPTED",
		"sql_state" => "HY000",
		"template"  => "This tablespace can't be encrypted, because one of table's schema has default encryption OFF and user doesn't have enough privilege.",
	],
	[
		"code"      => 3830,
		"symbol"    => "ER_TABLESPACE_CANNOT_BE_DECRYPTED",
		"sql_state" => "HY000",
		"template"  => "This tablespace can't be decrypted, because one of table's schema has default encryption ON and user doesn't have enough privilege.",
	],
	[
		"code"      => 3831,
		"symbol"    => "ER_TABLESPACE_TYPE_UNKNOWN",
		"sql_state" => "HY000",
		"template"  => "Cannot determine the type of the tablespace named '{#p1}'.",
	],
	[
		"code"      => 3832,
		"symbol"    => "ER_TARGET_TABLESPACE_UNENCRYPTED",
		"sql_state" => "HY000",
		"template"  => "Source tablespace is encrypted but target tablespace is not.",
	],
	[
		"code"      => 3833,
		"symbol"    => "ER_CANNOT_USE_ENCRYPTION_CLAUSE",
		"sql_state" => "HY000",
		"template"  => "ENCRYPTION clause is not valid for {#p1} tablespace.",
	],
	[
		"code"      => 3834,
		"symbol"    => "ER_INVALID_MULTIPLE_CLAUSES",
		"sql_state" => "HY000",
		"template"  => "Multiple {#p1} clauses",
	],
	[
		"code"      => 3835,
		"symbol"    => "ER_UNSUPPORTED_USE_OF_GRANT_AS",
		"sql_state" => "HY000",
		"template"  => "GRANT ... AS is currently supported only for global privileges.",
	],
	[
		"code"      => 3836,
		"symbol"    => "ER_UKNOWN_AUTH_ID_OR_ACCESS_DENIED_FOR_GRANT_AS",
		"sql_state" => "HY000",
		"template"  => "Either some of the authorization IDs in the AS clause are invalid or the current user lacks privileges to execute the statement.",
	],
	[
		"code"      => 3837,
		"symbol"    => "ER_DEPENDENT_BY_FUNCTIONAL_INDEX",
		"sql_state" => "HY000",
		"template"  => "Column '{#p1}' has a functional index dependency and cannot be dropped or renamed.",
	],
	[
		"code"      => 3838,
		"symbol"    => "ER_PLUGIN_NOT_EARLY",
		"sql_state" => "HY000",
		"template"  => "Plugin '{#p1}' is not to be used as an \"early\" plugin. Don't add it to --early-plugin-load, keyring migration etc.",
	],
	[
		"code"      => 3839,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_START_SUBDIR_PATH",
		"sql_state" => "HY000",
		"template"  => "Redo log archiving start prohibits path name in 'subdir' argument",
	],
	[
		"code"      => 3840,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_START_TIMEOUT",
		"sql_state" => "HY000",
		"template"  => "Redo log archiving start timed out",
	],
	[
		"code"      => 3841,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_DIRS_INVALID",
		"sql_state" => "HY000",
		"template"  => "Server variable 'innodb_redo_log_archive_dirs' is NULL or empty",
	],
	[
		"code"      => 3842,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_LABEL_NOT_FOUND",
		"sql_state" => "HY000",
		"template"  => "Label '{#p1}' not found in server variable 'innodb_redo_log_archive_dirs'",
	],
	[
		"code"      => 3843,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_DIR_EMPTY",
		"sql_state" => "HY000",
		"template"  => "Directory is empty after label '{#p1}' in server variable 'innodb_redo_log_archive_dirs'",
	],
	[
		"code"      => 3844,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_NO_SUCH_DIR",
		"sql_state" => "HY000",
		"template"  => "Redo log archive directory '{#p1}' does not exist or is not a directory",
	],
	[
		"code"      => 3845,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_DIR_CLASH",
		"sql_state" => "HY000",
		"template"  => "Redo log archive directory '{#p1}' is in, under, or over server directory '{#p2}' - '{#p3}'",
	],
	[
		"code"      => 3846,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_DIR_PERMISSIONS",
		"sql_state" => "HY000",
		"template"  => "Redo log archive directory '{#p1}' is accessible to all OS users",
	],
	[
		"code"      => 3847,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_FILE_CREATE",
		"sql_state" => "HY000",
		"template"  => "Cannot create redo log archive file '{#p1}' (OS errno: {p2} - {#p3})",
	],
	[
		"code"      => 3848,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_ACTIVE",
		"sql_state" => "HY000",
		"template"  => "Redo log archiving has been started on '{#p1}' - Call innodb_redo_log_archive_stop() first",
	],
	[
		"code"      => 3849,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_INACTIVE",
		"sql_state" => "HY000",
		"template"  => "Redo log archiving is not active",
	],
	[
		"code"      => 3850,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_FAILED",
		"sql_state" => "HY000",
		"template"  => "Redo log archiving failed: {#p1}",
	],
	[
		"code"      => 3851,
		"symbol"    => "ER_INNODB_REDO_LOG_ARCHIVE_SESSION",
		"sql_state" => "HY000",
		"template"  => "Redo log archiving has not been started by this session",
	],
	[
		"code"      => 3852,
		"symbol"    => "ER_STD_REGEX_ERROR",
		"sql_state" => "HY000",
		"template"  => "Regex error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3853,
		"symbol"    => "ER_INVALID_JSON_TYPE",
		"sql_state" => "22032",
		"template"  => "Invalid JSON type in argument {p1} to function {#p2}; an {#p3} is required.",
	],
	[
		"code"      => 3854,
		"symbol"    => "ER_CANNOT_CONVERT_STRING",
		"sql_state" => "HY000",
		"template"  => "Cannot convert string '{#p1}' from {#p2} to {#p3}",
	],
	[
		"code"      => 3855,
		"symbol"    => "ER_DEPENDENT_BY_PARTITION_FUNC",
		"sql_state" => "HY000",
		"template"  => "Column '{#p1}' has a partitioning function dependency and cannot be dropped or renamed.",
	],
	[
		"code"      => 3856,
		"symbol"    => "ER_WARN_DEPRECATED_FLOAT_AUTO_INCREMENT",
		"sql_state" => "HY000",
		"template"  => "AUTO_INCREMENT support for FLOAT/DOUBLE columns is deprecated and will be removed in a future release. Consider removing AUTO_INCREMENT from column '{#p1}'.",
	],
	[
		"code"      => 3857,
		"symbol"    => "ER_RPL_CANT_STOP_SLAVE_WHILE_LOCKED_BACKUP",
		"sql_state" => "HY000",
		"template"  => "Cannot stop the slave SQL thread while the instance is locked for backup. Try running `UNLOCK INSTANCE` first.",
	],
	[
		"code"      => 3858,
		"symbol"    => "ER_WARN_DEPRECATED_FLOAT_DIGITS",
		"sql_state" => "HY000",
		"template"  => "Specifying number of digits for floating point data types is deprecated and will be removed in a future release.",
	],
	[
		"code"      => 3859,
		"symbol"    => "ER_WARN_DEPRECATED_FLOAT_UNSIGNED",
		"sql_state" => "HY000",
		"template"  => "UNSIGNED for decimal and floating point data types is deprecated and support for it will be removed in a future release.",
	],
	[
		"code"      => 3860,
		"symbol"    => "ER_WARN_DEPRECATED_INTEGER_DISPLAY_WIDTH",
		"sql_state" => "HY000",
		"template"  => "Integer display width is deprecated and will be removed in a future release.",
	],
	[
		"code"      => 3861,
		"symbol"    => "ER_WARN_DEPRECATED_ZEROFILL",
		"sql_state" => "HY000",
		"template"  => "The ZEROFILL attribute is deprecated and will be removed in a future release. Use the LPAD function to zero-pad numbers, or store the formatted numbers in a CHAR column.",
	],
	[
		"code"      => 3862,
		"symbol"    => "ER_CLONE_DONOR",
		"sql_state" => "HY000",
		"template"  => "Clone Donor Error: {#p1}.",
	],
	[
		"code"      => 3863,
		"symbol"    => "ER_CLONE_PROTOCOL",
		"sql_state" => "HY000",
		"template"  => "Clone received unexpected response from Donor : {#p1}.",
	],
	[
		"code"      => 3864,
		"symbol"    => "ER_CLONE_DONOR_VERSION",
		"sql_state" => "HY000",
		"template"  => "Clone Donor MySQL version: {#p1} is different from Recipient MySQL version {#p2}.",
	],
	[
		"code"      => 3865,
		"symbol"    => "ER_CLONE_OS",
		"sql_state" => "HY000",
		"template"  => "Clone Donor OS: {#p1} is different from Recipient OS: {#p2}.",
	],
	[
		"code"      => 3866,
		"symbol"    => "ER_CLONE_PLATFORM",
		"sql_state" => "HY000",
		"template"  => "Clone Donor platform: {#p1} is different from Recipient platform: {#p2}.",
	],
	[
		"code"      => 3867,
		"symbol"    => "ER_CLONE_CHARSET",
		"sql_state" => "HY000",
		"template"  => "Clone Donor collation: {#p1} is unavailable in Recipient.",
	],
	[
		"code"      => 3868,
		"symbol"    => "ER_CLONE_CONFIG",
		"sql_state" => "HY000",
		"template"  => "Clone Configuration {#p1}: Donor value: {#p2} is different from Recipient value: {#p3}.",
	],
	[
		"code"      => 3869,
		"symbol"    => "ER_CLONE_SYS_CONFIG",
		"sql_state" => "HY000",
		"template"  => "Clone system configuration: {#p1}",
	],
	[
		"code"      => 3870,
		"symbol"    => "ER_CLONE_PLUGIN_MATCH",
		"sql_state" => "HY000",
		"template"  => "Clone Donor plugin {#p1} is not active in Recipient.",
	],
	[
		"code"      => 3871,
		"symbol"    => "ER_CLONE_LOOPBACK",
		"sql_state" => "HY000",
		"template"  => "Clone cannot use loop back connection while cloning into current data directory.",
	],
	[
		"code"      => 3872,
		"symbol"    => "ER_CLONE_ENCRYPTION",
		"sql_state" => "HY000",
		"template"  => "Clone needs SSL connection for encrypted table.",
	],
	[
		"code"      => 3873,
		"symbol"    => "ER_CLONE_DISK_SPACE",
		"sql_state" => "HY000",
		"template"  => "Clone estimated database size is {#p1}. Available space {#p2} is not enough.",
	],
	[
		"code"      => 3874,
		"symbol"    => "ER_CLONE_IN_PROGRESS",
		"sql_state" => "HY000",
		"template"  => "Concurrent clone in progress. Please try after clone is complete.",
	],
	[
		"code"      => 3875,
		"symbol"    => "ER_CLONE_DISALLOWED",
		"sql_state" => "HY000",
		"template"  => "The clone operation cannot be executed when {#p1}.",
	],
	[
		"code"      => 3876,
		"symbol"    => "ER_CANNOT_GRANT_ROLES_TO_ANONYMOUS_USER",
		"sql_state" => "HY000",
		"template"  => "Cannot grant roles to an anonymous user.",
	],
	[
		"code"      => 3878,
		"symbol"    => "ER_SECOND_PASSWORD_CANNOT_BE_EMPTY",
		"sql_state" => "HY000",
		"template"  => "Empty password can not be retained as second password for user '{#p1}'@'{#p2}'.",
	],
	[
		"code"      => 3879,
		"symbol"    => "ER_DB_ACCESS_DENIED",
		"sql_state" => "HY000",
		"template"  => "Access denied for AuthId `{#p1}`@`{#p2}` to database '{#p3}'.",
	],
	[
		"code"      => 3880,
		"symbol"    => "ER_DA_AUTH_ID_WITH_SYSTEM_USER_PRIV_IN_MANDATORY_ROLES",
		"sql_state" => "HY000",
		"template"  => "Cannot set mandatory_roles: AuthId `{#p1}`@`{#p2}` has '{#p3}' privilege.",
	],
	[
		"code"      => 3881,
		"symbol"    => "ER_DA_RPL_GTID_TABLE_CANNOT_OPEN",
		"sql_state" => "HY000",
		"template"  => "Gtid table is not ready to be used. Table '{#p1}.{#p2}' cannot be opened.",
	],
	[
		"code"      => 3882,
		"symbol"    => "ER_GEOMETRY_IN_UNKNOWN_LENGTH_UNIT",
		"sql_state" => "SU001",
		"template"  => "The geometry passed to function {#p1} is in SRID 0, which doesn't specify a length unit. Can't convert to '{#p2}'.",
	],
	[
		"code"      => 3883,
		"symbol"    => "ER_DA_PLUGIN_INSTALL_ERROR",
		"sql_state" => "HY000",
		"template"  => "Error installing plugin '{#p1}': {#p2}",
	],
	[
		"code"      => 3884,
		"symbol"    => "ER_NO_SESSION_TEMP",
		"sql_state" => "HY000",
		"template"  => "Storage engine could not allocate temporary tablespace for this session.",
	],
	[
		"code"      => 3885,
		"symbol"    => "ER_DA_UNKNOWN_ERROR_NUMBER",
		"sql_state" => "HY000",
		"template"  => "Got unknown error: {p1}",
	],
	[
		"code"      => 3886,
		"symbol"    => "ER_COLUMN_CHANGE_SIZE",
		"sql_state" => "HY000",
		"template"  => "Could not change column '{#p1}' of table '{#p2}'. The resulting size of index '{#p3}' would exceed the max key length of {p4} bytes.",
	],
	[
		"code"      => 3887,
		"symbol"    => "ER_REGEXP_INVALID_CAPTURE_GROUP_NAME",
		"sql_state" => "HY000",
		"template"  => "A capture group has an invalid name.",
	],
	[
		"code"      => 3888,
		"symbol"    => "ER_DA_SSL_LIBRARY_ERROR",
		"sql_state" => "HY000",
		"template"  => "Failed to set up SSL because of the following SSL library error: {#p1}",
	],
	[
		"code"      => 3889,
		"symbol"    => "ER_SECONDARY_ENGINE",
		"sql_state" => "HY000",
		"template"  => "Secondary engine operation failed. {#p1}.",
	],
	[
		"code"      => 3890,
		"symbol"    => "ER_SECONDARY_ENGINE_DDL",
		"sql_state" => "HY000",
		"template"  => "DDLs on a table with a secondary engine defined are not allowed.",
	],
	[
		"code"      => 3891,
		"symbol"    => "ER_INCORRECT_CURRENT_PASSWORD",
		"sql_state" => "HY000",
		"template"  => "Incorrect current password. Specify the correct password which has to be replaced.",
	],
	[
		"code"      => 3892,
		"symbol"    => "ER_MISSING_CURRENT_PASSWORD",
		"sql_state" => "HY000",
		"template"  => "Current password needs to be specified in the REPLACE clause in order to change it.",
	],
	[
		"code"      => 3893,
		"symbol"    => "ER_CURRENT_PASSWORD_NOT_REQUIRED",
		"sql_state" => "HY000",
		"template"  => "Do not specify the current password while changing it for other users.",
	],
	[
		"code"      => 3894,
		"symbol"    => "ER_PASSWORD_CANNOT_BE_RETAINED_ON_PLUGIN_CHANGE",
		"sql_state" => "HY000",
		"template"  => "Current password can not be retained for user '{#p1}'@'{#p2}' because authentication plugin is being changed.",
	],
	[
		"code"      => 3895,
		"symbol"    => "ER_CURRENT_PASSWORD_CANNOT_BE_RETAINED",
		"sql_state" => "HY000",
		"template"  => "Current password can not be retained for user '{#p1}'@'{#p2}' because new password is empty.",
	],
	[
		"code"      => 3896,
		"symbol"    => "ER_PARTIAL_REVOKES_EXIST",
		"sql_state" => "HY000",
		"template"  => "At least one partial revoke exists on a database. The system variable '@@partial_revokes' must be set to ON.",
	],
	[
		"code"      => 3897,
		"symbol"    => "ER_CANNOT_GRANT_SYSTEM_PRIV_TO_MANDATORY_ROLE",
		"sql_state" => "HY000",
		"template"  => "AuthId `{#p1}`@`{#p2}` is set as mandatory_roles. Cannot grant the '{#p3}' privilege.",
	],
	[
		"code"      => 3899,
		"symbol"    => "ER_UNSUPPORTED_SQL_MODE",
		"sql_state" => "HY000",
		"template"  => "sql_mode=0x%08x is not supported.",
	],
	[
		"code"      => 3900,
		"symbol"    => "ER_REGEXP_INVALID_FLAG",
		"sql_state" => "HY000",
		"template"  => "Invalid match mode flag in regular expression.",
	],
	[
		"code"      => 3901,
		"symbol"    => "ER_PARTIAL_REVOKE_AND_DB_GRANT_BOTH_EXISTS",
		"sql_state" => "HY000",
		"template"  => "'{#p1}' privilege for database '{#p2}' exists both as partial revoke and mysql.db simultaneously. It could mean that the 'mysql' schema is corrupted.",
	],
	[
		"code"      => 3902,
		"symbol"    => "ER_UNIT_NOT_FOUND",
		"sql_state" => "SU001",
		"template"  => "There's no unit of measure named '{#p1}'.",
	],
	[
		"code"      => 3903,
		"symbol"    => "ER_INVALID_JSON_VALUE_FOR_FUNC_INDEX",
		"sql_state" => "22018",
		"template"  => "Invalid JSON value for CAST for functional index '{#p1}'.",
	],
	[
		"code"      => 3904,
		"symbol"    => "ER_JSON_VALUE_OUT_OF_RANGE_FOR_FUNC_INDEX",
		"sql_state" => "22003",
		"template"  => "Out of range JSON value for CAST for functional index '{#p1}'.",
	],
	[
		"code"      => 3905,
		"symbol"    => "ER_EXCEEDED_MV_KEYS_NUM",
		"sql_state" => "HY000",
		"template"  => "Exceeded max number of values per record for multi-valued index '{#p1}' by {p2} value(s).",
	],
	[
		"code"      => 3906,
		"symbol"    => "ER_EXCEEDED_MV_KEYS_SPACE",
		"sql_state" => "HY000",
		"template"  => "Exceeded max total length of values per record for multi-valued index '{#p1}' by {p2} bytes.",
	],
	[
		"code"      => 3907,
		"symbol"    => "ER_FUNCTIONAL_INDEX_DATA_IS_TOO_LONG",
		"sql_state" => "22001",
		"template"  => "Data too long for functional index '{#p1}'.",
	],
	[
		"code"      => 3908,
		"symbol"    => "ER_WRONG_MVI_VALUE",
		"sql_state" => "HY000",
		"template"  => "Cannot store an array or an object in a scalar key part of the index '{#p1}'.",
	],
	[
		"code"      => 3909,
		"symbol"    => "ER_WARN_FUNC_INDEX_NOT_APPLICABLE",
		"sql_state" => "HY000",
		"template"  => "Cannot use functional index '{#p1}' due to type or collation conversion.",
	],
	[
		"code"      => 3910,
		"symbol"    => "ER_GRP_RPL_UDF_ERROR",
		"sql_state" => "HY000",
		"template"  => "The function '{#p1}' failed. {#p2}",
	],
	[
		"code"      => 3911,
		"symbol"    => "ER_UPDATE_GTID_PURGED_WITH_GR",
		"sql_state" => "HY000",
		"template"  => "Cannot update GTID_PURGED with the Group Replication plugin running",
	],
	[
		"code"      => 3913,
		"symbol"    => "ER_TABLE_NAME_CAUSES_TOO_LONG_PATH",
		"sql_state" => "HY000",
		"template"  => "Long database name and identifier for object resulted in a path length too long for table '{#p1}'. Please check the path limit for your OS.",
	],
	[
		"code"      => 3914,
		"symbol"    => "ER_AUDIT_LOG_INSUFFICIENT_PRIVILEGE",
		"sql_state" => "HY000",
		"template"  => "Request ignored for '{#p1}'@'{#p2}'. Role needed to perform operation: '{#p3}'",
	],
	[
		"code"      => 3916,
		"symbol"    => "ER_DA_GRP_RPL_STARTED_AUTO_REJOIN",
		"sql_state" => "HY000",
		"template"  => "Started auto-rejoin procedure attempt {p1} of {p2}",
	],
	[
		"code"      => 3917,
		"symbol"    => "ER_SYSVAR_CHANGE_DURING_QUERY",
		"sql_state" => "HY000",
		"template"  => "A plugin was loaded or unloaded during a query, a system variable table was changed.",
	],
	[
		"code"      => 3918,
		"symbol"    => "ER_GLOBSTAT_CHANGE_DURING_QUERY",
		"sql_state" => "HY000",
		"template"  => "A plugin was loaded or unloaded during a query, a global status variable was changed.",
	],
	[
		"code"      => 3919,
		"symbol"    => "ER_GRP_RPL_MESSAGE_SERVICE_INIT_FAILURE",
		"sql_state" => "HY000",
		"template"  => "The START GROUP_REPLICATION command failed to start its message service.",
	],
	[
		"code"      => 3920,
		"symbol"    => "ER_CHANGE_MASTER_WRONG_COMPRESSION_ALGORITHM_CLIENT",
		"sql_state" => "HY000",
		"template"  => "Invalid MASTER_COMPRESSION_ALGORITHMS '{#p1}' for channel '{#p2}'.",
	],
	[
		"code"      => 3921,
		"symbol"    => "ER_CHANGE_MASTER_WRONG_COMPRESSION_LEVEL_CLIENT",
		"sql_state" => "HY000",
		"template"  => "Invalid MASTER_ZSTD_COMPRESSION_LEVEL {p1} for channel '{#p2}'.",
	],
	[
		"code"      => 3922,
		"symbol"    => "ER_WRONG_COMPRESSION_ALGORITHM_CLIENT",
		"sql_state" => "HY000",
		"template"  => "Invalid compression algorithm '{#p1}'.",
	],
	[
		"code"      => 3923,
		"symbol"    => "ER_WRONG_COMPRESSION_LEVEL_CLIENT",
		"sql_state" => "HY000",
		"template"  => "Invalid zstd compression level for algorithm '{#p1}'.",
	],
	[
		"code"      => 3924,
		"symbol"    => "ER_CHANGE_MASTER_WRONG_COMPRESSION_ALGORITHM_LIST_CLIENT",
		"sql_state" => "HY000",
		"template"  => "Specified compression algorithm list '{#p1}' exceeds total count of 3 for channel '{#p2}'.",
	],
	[
		"code"      => 3925,
		"symbol"    => "ER_CLIENT_PRIVILEGE_CHECKS_USER_CANNOT_BE_ANONYMOUS",
		"sql_state" => "HY000",
		"template"  => "PRIVILEGE_CHECKS_USER for replication channel '{#p1}' was set to ``@`{#p2}`, but anonymous users are disallowed for PRIVILEGE_CHECKS_USER.",
	],
	[
		"code"      => 3926,
		"symbol"    => "ER_CLIENT_PRIVILEGE_CHECKS_USER_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "PRIVILEGE_CHECKS_USER for replication channel '{#p1}' was set to `{#p2}`@`{#p3}`, but this is not an existing user.",
	],
	[
		"code"      => 3927,
		"symbol"    => "ER_CLIENT_PRIVILEGE_CHECKS_USER_CORRUPT",
		"sql_state" => "HY000",
		"template"  => "Invalid, corrupted PRIVILEGE_CHECKS_USER was found in the replication configuration repository for channel '{#p1}'. Use CHANGE MASTER TO PRIVILEGE_CHECKS_USER to correct the configuration.",
	],
	[
		"code"      => 3928,
		"symbol"    => "ER_CLIENT_PRIVILEGE_CHECKS_USER_NEEDS_RPL_APPLIER_PRIV",
		"sql_state" => "HY000",
		"template"  => "PRIVILEGE_CHECKS_USER for replication channel '{#p1}' was set to `{#p2}`@`{#p3}`, but this user does not have REPLICATION_APPLIER privilege.",
	],
	[
		"code"      => 3929,
		"symbol"    => "ER_WARN_DA_PRIVILEGE_NOT_REGISTERED",
		"sql_state" => "HY000",
		"template"  => "Dynamic privilege '{#p1}' is not registered with the server.",
	],
	[
		"code"      => 3930,
		"symbol"    => "ER_CLIENT_KEYRING_UDF_KEY_INVALID",
		"sql_state" => "HY000",
		"template"  => "Function '{#p1}' failed because key is invalid.",
	],
	[
		"code"      => 3931,
		"symbol"    => "ER_CLIENT_KEYRING_UDF_KEY_TYPE_INVALID",
		"sql_state" => "HY000",
		"template"  => "Function '{#p1}' failed because key type is invalid.",
	],
	[
		"code"      => 3932,
		"symbol"    => "ER_CLIENT_KEYRING_UDF_KEY_TOO_LONG",
		"sql_state" => "HY000",
		"template"  => "Function '{#p1}' failed because key length is too long.",
	],
	[
		"code"      => 3933,
		"symbol"    => "ER_CLIENT_KEYRING_UDF_KEY_TYPE_TOO_LONG",
		"sql_state" => "HY000",
		"template"  => "Function '{#p1}' failed because key type is too long.",
	],
];

return array_merge($previous, $new);
