<?php

$previous = require __DIR__ . '/server_5.6.php';

$new = [
	[
		"code"      => 1101,
		"symbol"    => "ER_BLOB_CANT_HAVE_DEFAULT",
		"sql_state" => "42000",
		"template"  => "BLOB, TEXT, GEOMETRY or JSON column '{#p1}' can't have a default value",
	],
	[
		"code"      => 1175,
		"symbol"    => "ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE",
		"sql_state" => "HY000",
		"template"  => "You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column. {#p1}",
	],
	[
		"code"      => 1426,
		"symbol"    => "ER_TOO_BIG_PRECISION",
		"sql_state" => "42000",
		"template"  => "Too-big precision {p1} specified for '{#p2}'. Maximum is {p3}.",
	],
	[
		"code"      => 1506,
		"symbol"    => "ER_FOREIGN_KEY_ON_PARTITIONED",
		"sql_state" => "HY000",
		"template"  => "Foreign keys are not yet supported in conjunction with partitioning",
	],
	[
		"code"      => 1584,
		"symbol"    => "ER_WRONG_PARAMETERS_TO_STORED_FCT",
		"sql_state" => "42000",
		"template"  => "Incorrect parameters in the call to stored function {#p1}",
	],
	[
		"code"      => 1777,
		"symbol"    => "ER_AUTO_POSITION_REQUIRES_GTID_MODE_NOT_OFF",
		"sql_state" => "HY000",
		"template"  => "CHANGE MASTER TO MASTER_AUTO_POSITION = 1 cannot be executed because @@GLOBAL.GTID_MODE = OFF.",
	],
	[
		"code"      => 1778,
		"symbol"    => "ER_CANT_DO_IMPLICIT_COMMIT_IN_TRX_WHEN_GTID_NEXT_IS_SET",
		"sql_state" => "HY000",
		"template"  => "Cannot execute statements with implicit commit inside a transaction when @@SESSION.GTID_NEXT == 'UUID:NUMBER'.",
	],
	[
		"code"      => 1779,
		"symbol"    => "ER_GTID_MODE_ON_REQUIRES_ENFORCE_GTID_CONSISTENCY_ON",
		"sql_state" => "HY000",
		"template"  => "GTID_MODE = ON requires ENFORCE_GTID_CONSISTENCY = ON.",
	],
	[
		"code"      => 1780,
		"symbol"    => "ER_GTID_MODE_REQUIRES_BINLOG",
		"sql_state" => "HY000",
		"template"  => "@@GLOBAL.GTID_MODE = ON or ON_PERMISSIVE or OFF_PERMISSIVE requires --log-bin and --log-slave-updates.",
	],
	[
		"code"      => 1784,
		"symbol"    => "ER_FOUND_GTID_EVENT_WHEN_GTID_MODE_IS_OFF__UNUSED",
		"sql_state" => "HY000",
		"template"  => "Found a Gtid_log_event when @@GLOBAL.GTID_MODE = OFF.",
	],
	[
		"code"      => 1785,
		"symbol"    => "ER_GTID_UNSAFE_NON_TRANSACTIONAL_TABLE",
		"sql_state" => "HY000",
		"template"  => "Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.",
	],
	[
		"code"      => 1786,
		"symbol"    => "ER_GTID_UNSAFE_CREATE_SELECT",
		"sql_state" => "HY000",
		"template"  => "Statement violates GTID consistency: CREATE TABLE ... SELECT.",
	],
	[
		"code"      => 1787,
		"symbol"    => "ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION",
		"sql_state" => "HY000",
		"template"  => "Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context. These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.",
	],
	[
		"code"      => 1788,
		"symbol"    => "ER_GTID_MODE_CAN_ONLY_CHANGE_ONE_STEP_AT_A_TIME",
		"sql_state" => "HY000",
		"template"  => "The value of @@GLOBAL.GTID_MODE can only be changed one step at a time: OFF <-> OFF_PERMISSIVE <-> ON_PERMISSIVE <-> ON. Also note that this value must be stepped up or down simultaneously on all servers. See the Manual for instructions.",
	],
	[
		"code"      => 1812,
		"symbol"    => "ER_TABLESPACE_MISSING",
		"sql_state" => "HY000",
		"template"  => "Tablespace is missing for table {#p1}.",
	],
	[
		"code"      => 1813,
		"symbol"    => "ER_TABLESPACE_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Tablespace '{#p1}' exists.",
	],
	[
		"code"      => 1816,
		"symbol"    => "ER_INNODB_IMPORT_ERROR",
		"sql_state" => "HY000",
		"template"  => "ALTER TABLE {#p1} IMPORT TABLESPACE failed with error {p2} : '{#p3}'",
	],
	[
		"code"      => 1818,
		"symbol"    => "ER_INVALID_YEAR_COLUMN_LENGTH",
		"sql_state" => "HY000",
		"template"  => "Supports only YEAR or YEAR(4) column.",
	],
	[
		"code"      => 1820,
		"symbol"    => "ER_MUST_CHANGE_PASSWORD",
		"sql_state" => "HY000",
		"template"  => "You must reset your password using ALTER USER statement before executing this statement.",
	],
	[
		"code"      => 1906,
		"symbol"    => "ER_SLAVE_IO_THREAD_MUST_STOP",
		"sql_state" => "HY000",
		"template"  => "This operation cannot be performed with a running slave io thread; run STOP SLAVE IO_THREAD first.",
	],
	[
		"code"      => 3000,
		"symbol"    => "ER_FILE_CORRUPT",
		"sql_state" => "HY000",
		"template"  => "File {#p1} is corrupted",
	],
	[
		"code"      => 3001,
		"symbol"    => "ER_ERROR_ON_MASTER",
		"sql_state" => "HY000",
		"template"  => "Query partially completed on the master (error on master: {p1}) and was aborted. There is a chance that your master is inconsistent at this point. If you are sure that your master is ok, run this query manually on the slave and then restart the slave with SET GLOBAL SQL_SLAVE_SKIP_COUNTER=1; START SLAVE;. Query:'{#p2}'",
	],
	[
		"code"      => 3002,
		"symbol"    => "ER_INCONSISTENT_ERROR",
		"sql_state" => "HY000",
		"template"  => "Query caused different errors on master and slave. Error on master: message (format)='{#p1}' error code={p2}; Error on slave:actual message='{#p3}', error code={p4}. Default database:'{#p5}'. Query:'{#p6}'",
	],
	[
		"code"      => 3003,
		"symbol"    => "ER_STORAGE_ENGINE_NOT_LOADED",
		"sql_state" => "HY000",
		"template"  => "Storage engine for table '{#p1}'.'{#p2}' is not loaded.",
	],
	[
		"code"      => 3004,
		"symbol"    => "ER_GET_STACKED_DA_WITHOUT_ACTIVE_HANDLER",
		"sql_state" => "0Z002",
		"template"  => "GET STACKED DIAGNOSTICS when handler not active",
	],
	[
		"code"      => 3006,
		"symbol"    => "ER_BINLOG_UNSAFE_FULLTEXT_PLUGIN",
		"sql_state" => "HY000",
		"template"  => "Statement is unsafe because it uses a fulltext parser plugin which may not return the same value on the slave.",
	],
	[
		"code"      => 3007,
		"symbol"    => "ER_CANNOT_DISCARD_TEMPORARY_TABLE",
		"sql_state" => "HY000",
		"template"  => "Cannot DISCARD/IMPORT tablespace associated with temporary table",
	],
	[
		"code"      => 3008,
		"symbol"    => "ER_FK_DEPTH_EXCEEDED",
		"sql_state" => "HY000",
		"template"  => "Foreign key cascade delete/update exceeds max depth of {p1}.",
	],
	[
		"code"      => 3009,
		"symbol"    => "ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE_V2",
		"sql_state" => "HY000",
		"template"  => "Column count of {#p1}.{#p2} is wrong. Expected {p3}, found {p4}. Created with MySQL {p5}, now running {p6}. Please use mysql_upgrade to fix this error.",
	],
	[
		"code"      => 3010,
		"symbol"    => "ER_WARN_TRIGGER_DOESNT_HAVE_CREATED",
		"sql_state" => "HY000",
		"template"  => "Trigger {#p1}.{#p2}.{#p3} does not have CREATED attribute.",
	],
	[
		"code"      => 3011,
		"symbol"    => "ER_REFERENCED_TRG_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "Referenced trigger '{#p1}' for the given action time and event type does not exist.",
	],
	[
		"code"      => 3012,
		"symbol"    => "ER_EXPLAIN_NOT_SUPPORTED",
		"sql_state" => "HY000",
		"template"  => "EXPLAIN FOR CONNECTION command is supported only for SELECT/UPDATE/INSERT/DELETE/REPLACE",
	],
	[
		"code"      => 3013,
		"symbol"    => "ER_INVALID_FIELD_SIZE",
		"sql_state" => "HY000",
		"template"  => "Invalid size for column '{#p1}'.",
	],
	[
		"code"      => 3014,
		"symbol"    => "ER_MISSING_HA_CREATE_OPTION",
		"sql_state" => "HY000",
		"template"  => "Table storage engine '{#p1}' found required create option missing",
	],
	[
		"code"      => 3015,
		"symbol"    => "ER_ENGINE_OUT_OF_MEMORY",
		"sql_state" => "HY000",
		"template"  => "Out of memory in storage engine '{#p1}'.",
	],
	[
		"code"      => 3016,
		"symbol"    => "ER_PASSWORD_EXPIRE_ANONYMOUS_USER",
		"sql_state" => "HY000",
		"template"  => "The password for anonymous user cannot be expired.",
	],
	[
		"code"      => 3017,
		"symbol"    => "ER_SLAVE_SQL_THREAD_MUST_STOP",
		"sql_state" => "HY000",
		"template"  => "This operation cannot be performed with a running slave sql thread; run STOP SLAVE SQL_THREAD first",
	],
	[
		"code"      => 3018,
		"symbol"    => "ER_NO_FT_MATERIALIZED_SUBQUERY",
		"sql_state" => "HY000",
		"template"  => "Cannot create FULLTEXT index on materialized subquery",
	],
	[
		"code"      => 3019,
		"symbol"    => "ER_INNODB_UNDO_LOG_FULL",
		"sql_state" => "HY000",
		"template"  => "Undo Log error: {#p1}",
	],
	[
		"code"      => 3020,
		"symbol"    => "ER_INVALID_ARGUMENT_FOR_LOGARITHM",
		"sql_state" => "2201E",
		"template"  => "Invalid argument for logarithm",
	],
	[
		"code"      => 3021,
		"symbol"    => "ER_SLAVE_CHANNEL_IO_THREAD_MUST_STOP",
		"sql_state" => "HY000",
		"template"  => "This operation cannot be performed with a running slave io thread; run STOP SLAVE IO_THREAD FOR CHANNEL '{#p1}' first.",
	],
	[
		"code"      => 3022,
		"symbol"    => "ER_WARN_OPEN_TEMP_TABLES_MUST_BE_ZERO",
		"sql_state" => "HY000",
		"template"  => "This operation may not be safe when the slave has temporary tables. The tables will be kept open until the server restarts or until the tables are deleted by any replicated DROP statement. Suggest to wait until slave_open_temp_tables = 0.",
	],
	[
		"code"      => 3023,
		"symbol"    => "ER_WARN_ONLY_MASTER_LOG_FILE_NO_POS",
		"sql_state" => "HY000",
		"template"  => "CHANGE MASTER TO with a MASTER_LOG_FILE clause but no MASTER_LOG_POS clause may not be safe. The old position value may not be valid for the new binary log file.",
	],
	[
		"code"      => 3024,
		"symbol"    => "ER_QUERY_TIMEOUT",
		"sql_state" => "HY000",
		"template"  => "Query execution was interrupted, maximum statement execution time exceeded",
	],
	[
		"code"      => 3025,
		"symbol"    => "ER_NON_RO_SELECT_DISABLE_TIMER",
		"sql_state" => "HY000",
		"template"  => "Select is not a read only statement, disabling timer",
	],
	[
		"code"      => 3026,
		"symbol"    => "ER_DUP_LIST_ENTRY",
		"sql_state" => "HY000",
		"template"  => "Duplicate entry '{#p1}'.",
	],
	[
		"code"      => 3027,
		"symbol"    => "ER_SQL_MODE_NO_EFFECT",
		"sql_state" => "HY000",
		"template"  => "'{#p1}' mode no longer has any effect. Use STRICT_ALL_TABLES or STRICT_TRANS_TABLES instead.",
	],
	[
		"code"      => 3028,
		"symbol"    => "ER_AGGREGATE_ORDER_FOR_UNION",
		"sql_state" => "HY000",
		"template"  => "Expression #{p1} of ORDER BY contains aggregate function and applies to a UNION",
	],
	[
		"code"      => 3029,
		"symbol"    => "ER_AGGREGATE_ORDER_NON_AGG_QUERY",
		"sql_state" => "HY000",
		"template"  => "Expression #{p1} of ORDER BY contains aggregate function and applies to the result of a non-aggregated query",
	],
	[
		"code"      => 3030,
		"symbol"    => "ER_SLAVE_WORKER_STOPPED_PREVIOUS_THD_ERROR",
		"sql_state" => "HY000",
		"template"  => "Slave worker has stopped after at least one previous worker encountered an error when slave-preserve-commit-order was enabled. To preserve commit order, the last transaction executed by this thread has not been committed. When restarting the slave after fixing any failed threads, you should fix this worker as well.",
	],
	[
		"code"      => 3031,
		"symbol"    => "ER_DONT_SUPPORT_SLAVE_PRESERVE_COMMIT_ORDER",
		"sql_state" => "HY000",
		"template"  => "slave_preserve_commit_order is not supported {#p1}.",
	],
	[
		"code"      => 3032,
		"symbol"    => "ER_SERVER_OFFLINE_MODE",
		"sql_state" => "HY000",
		"template"  => "The server is currently in offline mode",
	],
	[
		"code"      => 3033,
		"symbol"    => "ER_GIS_DIFFERENT_SRIDS",
		"sql_state" => "HY000",
		"template"  => "Binary geometry function {#p1} given two geometries of different srids: {p2} and {p3}, which should have been identical.",
	],
	[
		"code"      => 3034,
		"symbol"    => "ER_GIS_UNSUPPORTED_ARGUMENT",
		"sql_state" => "HY000",
		"template"  => "Calling geometry function {#p1} with unsupported types of arguments.",
	],
	[
		"code"      => 3035,
		"symbol"    => "ER_GIS_UNKNOWN_ERROR",
		"sql_state" => "HY000",
		"template"  => "Unknown GIS error occured in function {#p1}.",
	],
	[
		"code"      => 3036,
		"symbol"    => "ER_GIS_UNKNOWN_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Unknown exception caught in GIS function {#p1}.",
	],
	[
		"code"      => 3037,
		"symbol"    => "ER_GIS_INVALID_DATA",
		"sql_state" => "22023",
		"template"  => "Invalid GIS data provided to function {#p1}.",
	],
	[
		"code"      => 3038,
		"symbol"    => "ER_BOOST_GEOMETRY_EMPTY_INPUT_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "The geometry has no data in function {#p1}.",
	],
	[
		"code"      => 3039,
		"symbol"    => "ER_BOOST_GEOMETRY_CENTROID_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Unable to calculate centroid because geometry is empty in function {#p1}.",
	],
	[
		"code"      => 3040,
		"symbol"    => "ER_BOOST_GEOMETRY_OVERLAY_INVALID_INPUT_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Geometry overlay calculation error: geometry data is invalid in function {#p1}.",
	],
	[
		"code"      => 3041,
		"symbol"    => "ER_BOOST_GEOMETRY_TURN_INFO_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Geometry turn info calculation error: geometry data is invalid in function {#p1}.",
	],
	[
		"code"      => 3042,
		"symbol"    => "ER_BOOST_GEOMETRY_SELF_INTERSECTION_POINT_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Analysis procedures of intersection points interrupted unexpectedly in function {#p1}.",
	],
	[
		"code"      => 3043,
		"symbol"    => "ER_BOOST_GEOMETRY_UNKNOWN_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Unknown exception thrown in function {#p1}.",
	],
	[
		"code"      => 3044,
		"symbol"    => "ER_STD_BAD_ALLOC_ERROR",
		"sql_state" => "HY000",
		"template"  => "Memory allocation error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3045,
		"symbol"    => "ER_STD_DOMAIN_ERROR",
		"sql_state" => "HY000",
		"template"  => "Domain error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3046,
		"symbol"    => "ER_STD_LENGTH_ERROR",
		"sql_state" => "HY000",
		"template"  => "Length error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3047,
		"symbol"    => "ER_STD_INVALID_ARGUMENT",
		"sql_state" => "HY000",
		"template"  => "Invalid argument error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3048,
		"symbol"    => "ER_STD_OUT_OF_RANGE_ERROR",
		"sql_state" => "HY000",
		"template"  => "Out of range error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3049,
		"symbol"    => "ER_STD_OVERFLOW_ERROR",
		"sql_state" => "HY000",
		"template"  => "Overflow error error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3050,
		"symbol"    => "ER_STD_RANGE_ERROR",
		"sql_state" => "HY000",
		"template"  => "Range error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3051,
		"symbol"    => "ER_STD_UNDERFLOW_ERROR",
		"sql_state" => "HY000",
		"template"  => "Underflow error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3052,
		"symbol"    => "ER_STD_LOGIC_ERROR",
		"sql_state" => "HY000",
		"template"  => "Logic error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3053,
		"symbol"    => "ER_STD_RUNTIME_ERROR",
		"sql_state" => "HY000",
		"template"  => "Runtime error: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3054,
		"symbol"    => "ER_STD_UNKNOWN_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Unknown exception: {#p1} in function {#p2}.",
	],
	[
		"code"      => 3055,
		"symbol"    => "ER_GIS_DATA_WRONG_ENDIANESS",
		"sql_state" => "HY000",
		"template"  => "Geometry byte string must be little endian.",
	],
	[
		"code"      => 3056,
		"symbol"    => "ER_CHANGE_MASTER_PASSWORD_LENGTH",
		"sql_state" => "HY000",
		"template"  => "The password provided for the replication user exceeds the maximum length of 32 characters",
	],
	[
		"code"      => 3057,
		"symbol"    => "ER_USER_LOCK_WRONG_NAME",
		"sql_state" => "42000",
		"template"  => "Incorrect user-level lock name '{#p1}'.",
	],
	[
		"code"      => 3058,
		"symbol"    => "ER_USER_LOCK_DEADLOCK",
		"sql_state" => "HY000",
		"template"  => "Deadlock found when trying to get user-level lock; try rolling back transaction/releasing locks and restarting lock acquisition.",
	],
	[
		"code"      => 3059,
		"symbol"    => "ER_REPLACE_INACCESSIBLE_ROWS",
		"sql_state" => "HY000",
		"template"  => "REPLACE cannot be executed as it requires deleting rows that are not in the view",
	],
	[
		"code"      => 3060,
		"symbol"    => "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_GIS",
		"sql_state" => "HY000",
		"template"  => "Do not support online operation on table with GIS index",
	],
	[
		"code"      => 3061,
		"symbol"    => "ER_ILLEGAL_USER_VAR",
		"sql_state" => "42000",
		"template"  => "User variable name '{#p1}' is illegal",
	],
	[
		"code"      => 3062,
		"symbol"    => "ER_GTID_MODE_OFF",
		"sql_state" => "HY000",
		"template"  => "Cannot {#p1} when GTID_MODE = OFF.",
	],
	[
		"code"      => 3063,
		"symbol"    => "ER_UNSUPPORTED_BY_REPLICATION_THREAD",
		"sql_state" => "HY000",
		"template"  => "Cannot {#p1} from a replication slave thread.",
	],
	[
		"code"      => 3064,
		"symbol"    => "ER_INCORRECT_TYPE",
		"sql_state" => "HY000",
		"template"  => "Incorrect type for argument {#p1} in function {#p2}.",
	],
	[
		"code"      => 3065,
		"symbol"    => "ER_FIELD_IN_ORDER_NOT_SELECT",
		"sql_state" => "HY000",
		"template"  => "Expression #{p1} of ORDER BY clause is not in SELECT list, references column '{#p2}' which is not in SELECT list; this is incompatible with {#p3}",
	],
	[
		"code"      => 3066,
		"symbol"    => "ER_AGGREGATE_IN_ORDER_NOT_SELECT",
		"sql_state" => "HY000",
		"template"  => "Expression #{p1} of ORDER BY clause is not in SELECT list, contains aggregate function; this is incompatible with {#p2}",
	],
	[
		"code"      => 3067,
		"symbol"    => "ER_INVALID_RPL_WILD_TABLE_FILTER_PATTERN",
		"sql_state" => "HY000",
		"template"  => "Supplied filter list contains a value which is not in the required format 'db_pattern.table_pattern'",
	],
	[
		"code"      => 3068,
		"symbol"    => "ER_NET_OK_PACKET_TOO_LARGE",
		"sql_state" => "08S01",
		"template"  => "OK packet too large",
	],
	[
		"code"      => 3069,
		"symbol"    => "ER_INVALID_JSON_DATA",
		"sql_state" => "HY000",
		"template"  => "Invalid JSON data provided to function {#p1}: {#p2}",
	],
	[
		"code"      => 3070,
		"symbol"    => "ER_INVALID_GEOJSON_MISSING_MEMBER",
		"sql_state" => "HY000",
		"template"  => "Invalid GeoJSON data provided to function {#p1}: Missing required member '{#p2}'",
	],
	[
		"code"      => 3071,
		"symbol"    => "ER_INVALID_GEOJSON_WRONG_TYPE",
		"sql_state" => "HY000",
		"template"  => "Invalid GeoJSON data provided to function {#p1}: Member '{#p2}' must be of type '{#p3}'",
	],
	[
		"code"      => 3072,
		"symbol"    => "ER_INVALID_GEOJSON_UNSPECIFIED",
		"sql_state" => "HY000",
		"template"  => "Invalid GeoJSON data provided to function {#p1}",
	],
	[
		"code"      => 3073,
		"symbol"    => "ER_DIMENSION_UNSUPPORTED",
		"sql_state" => "HY000",
		"template"  => "Unsupported number of coordinate dimensions in function {#p1}: Found {p2}, expected {p3}",
	],
	[
		"code"      => 3074,
		"symbol"    => "ER_SLAVE_CHANNEL_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "Slave channel '{#p1}' does not exist.",
	],
	[
		"code"      => 3075,
		"symbol"    => "ER_SLAVE_MULTIPLE_CHANNELS_HOST_PORT",
		"sql_state" => "HY000",
		"template"  => "A slave channel '{#p1}' already exists for the given host and port combination.",
	],
	[
		"code"      => 3076,
		"symbol"    => "ER_SLAVE_CHANNEL_NAME_INVALID_OR_TOO_LONG",
		"sql_state" => "HY000",
		"template"  => "Couldn't create channel: Channel name is either invalid or too long.",
	],
	[
		"code"      => 3077,
		"symbol"    => "ER_SLAVE_NEW_CHANNEL_WRONG_REPOSITORY",
		"sql_state" => "HY000",
		"template"  => "To have multiple channels, repository cannot be of type FILE; Please check the repository configuration and convert them to TABLE.",
	],
	[
		"code"      => 3078,
		"symbol"    => "ER_SLAVE_CHANNEL_DELETE",
		"sql_state" => "HY000",
		"template"  => "Cannot delete slave info objects for channel '{#p1}'.",
	],
	[
		"code"      => 3079,
		"symbol"    => "ER_SLAVE_MULTIPLE_CHANNELS_CMD",
		"sql_state" => "HY000",
		"template"  => "Multiple channels exist on the slave. Please provide channel name as an argument.",
	],
	[
		"code"      => 3080,
		"symbol"    => "ER_SLAVE_MAX_CHANNELS_EXCEEDED",
		"sql_state" => "HY000",
		"template"  => "Maximum number of replication channels allowed exceeded.",
	],
	[
		"code"      => 3081,
		"symbol"    => "ER_SLAVE_CHANNEL_MUST_STOP",
		"sql_state" => "HY000",
		"template"  => "This operation cannot be performed with running replication threads; run STOP SLAVE FOR CHANNEL '{#p1}' first",
	],
	[
		"code"      => 3082,
		"symbol"    => "ER_SLAVE_CHANNEL_NOT_RUNNING",
		"sql_state" => "HY000",
		"template"  => "This operation requires running replication threads; configure slave and run START SLAVE FOR CHANNEL '{#p1}'",
	],
	[
		"code"      => 3083,
		"symbol"    => "ER_SLAVE_CHANNEL_WAS_RUNNING",
		"sql_state" => "HY000",
		"template"  => "Replication thread(s) for channel '{#p1}' are already runnning.",
	],
	[
		"code"      => 3084,
		"symbol"    => "ER_SLAVE_CHANNEL_WAS_NOT_RUNNING",
		"sql_state" => "HY000",
		"template"  => "Replication thread(s) for channel '{#p1}' are already stopped.",
	],
	[
		"code"      => 3085,
		"symbol"    => "ER_SLAVE_CHANNEL_SQL_THREAD_MUST_STOP",
		"sql_state" => "HY000",
		"template"  => "This operation cannot be performed with a running slave sql thread; run STOP SLAVE SQL_THREAD FOR CHANNEL '{#p1}' first.",
	],
	[
		"code"      => 3086,
		"symbol"    => "ER_SLAVE_CHANNEL_SQL_SKIP_COUNTER",
		"sql_state" => "HY000",
		"template"  => "When sql_slave_skip_counter > 0, it is not allowed to start more than one SQL thread by using 'START SLAVE [SQL_THREAD]'. Value of sql_slave_skip_counter can only be used by one SQL thread at a time. Please use 'START SLAVE [SQL_THREAD] FOR CHANNEL' to start the SQL thread which will use the value of sql_slave_skip_counter.",
	],
	[
		"code"      => 3087,
		"symbol"    => "ER_WRONG_FIELD_WITH_GROUP_V2",
		"sql_state" => "HY000",
		"template"  => "Expression #{p1} of {#p2} is not in GROUP BY clause and contains nonaggregated column '{#p3}' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by",
	],
	[
		"code"      => 3088,
		"symbol"    => "ER_MIX_OF_GROUP_FUNC_AND_FIELDS_V2",
		"sql_state" => "HY000",
		"template"  => "In aggregated query without GROUP BY, expression #{p1} of {#p2} contains nonaggregated column '{#p3}'; this is incompatible with sql_mode=only_full_group_by",
	],
	[
		"code"      => 3089,
		"symbol"    => "ER_WARN_DEPRECATED_SYSVAR_UPDATE",
		"sql_state" => "HY000",
		"template"  => "Updating '{#p1}' is deprecated. It will be made read-only in a future release.",
	],
	[
		"code"      => 3090,
		"symbol"    => "ER_WARN_DEPRECATED_SQLMODE",
		"sql_state" => "HY000",
		"template"  => "Changing sql mode '{#p1}' is deprecated. It will be removed in a future release.",
	],
	[
		"code"      => 3091,
		"symbol"    => "ER_CANNOT_LOG_PARTIAL_DROP_DATABASE_WITH_GTID",
		"sql_state" => "HY000",
		"template"  => "DROP DATABASE failed; some tables may have been dropped but the database directory remains. The GTID has not been added to GTID_EXECUTED and the statement was not written to the binary log. Fix this as follows: (1) remove all files from the database directory {#p1}; (2) SET GTID_NEXT='{#p2}'; (3) DROP DATABASE `{#p3}`.",
	],
	[
		"code"      => 3092,
		"symbol"    => "ER_GROUP_REPLICATION_CONFIGURATION",
		"sql_state" => "HY000",
		"template"  => "The server is not configured properly to be an active member of the group. Please see more details on error log.",
	],
	[
		"code"      => 3093,
		"symbol"    => "ER_GROUP_REPLICATION_RUNNING",
		"sql_state" => "HY000",
		"template"  => "The START GROUP_REPLICATION command failed since the group is already running.",
	],
	[
		"code"      => 3094,
		"symbol"    => "ER_GROUP_REPLICATION_APPLIER_INIT_ERROR",
		"sql_state" => "HY000",
		"template"  => "The START GROUP_REPLICATION command failed as the applier module failed to start.",
	],
	[
		"code"      => 3095,
		"symbol"    => "ER_GROUP_REPLICATION_STOP_APPLIER_THREAD_TIMEOUT",
		"sql_state" => "HY000",
		"template"  => "The STOP GROUP_REPLICATION command execution is incomplete: The applier thread got the stop signal while it was busy. The applier thread will stop once the current task is complete.",
	],
	[
		"code"      => 3096,
		"symbol"    => "ER_GROUP_REPLICATION_COMMUNICATION_LAYER_SESSION_ERROR",
		"sql_state" => "HY000",
		"template"  => "The START GROUP_REPLICATION command failed as there was an error when initializing the group communication layer.",
	],
	[
		"code"      => 3097,
		"symbol"    => "ER_GROUP_REPLICATION_COMMUNICATION_LAYER_JOIN_ERROR",
		"sql_state" => "HY000",
		"template"  => "The START GROUP_REPLICATION command failed as there was an error when joining the communication group.",
	],
	[
		"code"      => 3098,
		"symbol"    => "ER_BEFORE_DML_VALIDATION_ERROR",
		"sql_state" => "HY000",
		"template"  => "The table does not comply with the requirements by an external plugin.",
	],
	[
		"code"      => 3099,
		"symbol"    => "ER_PREVENTS_VARIABLE_WITHOUT_RBR",
		"sql_state" => "HY000",
		"template"  => "Cannot change the value of variable {#p1} without binary log format as ROW.",
	],
	[
		"code"      => 3100,
		"symbol"    => "ER_RUN_HOOK_ERROR",
		"sql_state" => "HY000",
		"template"  => "Error on observer while running replication hook '{#p1}'.",
	],
	[
		"code"      => 3101,
		"symbol"    => "ER_TRANSACTION_ROLLBACK_DURING_COMMIT",
		"sql_state" => "HY000",
		"template"  => "Plugin instructed the server to rollback the current transaction.",
	],
	[
		"code"      => 3102,
		"symbol"    => "ER_GENERATED_COLUMN_FUNCTION_IS_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "Expression of generated column '{#p1}' contains a disallowed function.",
	],
	[
		"code"      => 3103,
		"symbol"    => "ER_KEY_BASED_ON_GENERATED_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Key/Index cannot be defined on a virtual generated column.",
	],
	[
		"code"      => 3103,
		"symbol"    => "ER_UNSUPPORTED_ALTER_INPLACE_ON_VIRTUAL_COLUMN",
		"sql_state" => "HY000",
		"template"  => "INPLACE ADD or DROP of virtual columns cannot be combined with other ALTER TABLE actions",
	],
	[
		"code"      => 3104,
		"symbol"    => "ER_WRONG_FK_OPTION_FOR_GENERATED_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Cannot define foreign key with {#p1} clause on a generated column.",
	],
	[
		"code"      => 3105,
		"symbol"    => "ER_NON_DEFAULT_VALUE_FOR_GENERATED_COLUMN",
		"sql_state" => "HY000",
		"template"  => "The value specified for generated column '{#p1}' in table '{#p2}' is not allowed.",
	],
	[
		"code"      => 3106,
		"symbol"    => "ER_UNSUPPORTED_ACTION_ON_GENERATED_COLUMN",
		"sql_state" => "HY000",
		"template"  => "'{#p1}' is not supported for generated columns.",
	],
	[
		"code"      => 3107,
		"symbol"    => "ER_GENERATED_COLUMN_NON_PRIOR",
		"sql_state" => "HY000",
		"template"  => "Generated column can refer only to generated columns defined prior to it.",
	],
	[
		"code"      => 3108,
		"symbol"    => "ER_DEPENDENT_BY_GENERATED_COLUMN",
		"sql_state" => "HY000",
		"template"  => "Column '{#p1}' has a generated column dependency.",
	],
	[
		"code"      => 3109,
		"symbol"    => "ER_GENERATED_COLUMN_REF_AUTO_INC",
		"sql_state" => "HY000",
		"template"  => "Generated column '{#p1}' cannot refer to auto-increment column.",
	],
	[
		"code"      => 3110,
		"symbol"    => "ER_FEATURE_NOT_AVAILABLE",
		"sql_state" => "HY000",
		"template"  => "The '{#p1}' feature is not available; you need to remove '{#p2}' or use MySQL built with '{#p3}'",
	],
	[
		"code"      => 3111,
		"symbol"    => "ER_CANT_SET_GTID_MODE",
		"sql_state" => "HY000",
		"template"  => "SET @@GLOBAL.GTID_MODE = {#p1} is not allowed because {#p2}.",
	],
	[
		"code"      => 3112,
		"symbol"    => "ER_CANT_USE_AUTO_POSITION_WITH_GTID_MODE_OFF",
		"sql_state" => "HY000",
		"template"  => "The replication receiver thread{#p1} cannot start in AUTO_POSITION mode: this server uses @@GLOBAL.GTID_MODE = OFF.",
	],
	[
		"code"      => 3113,
		"symbol"    => "ER_CANT_REPLICATE_ANONYMOUS_WITH_AUTO_POSITION",
		"sql_state" => "HY000",
		"template"  => "Cannot replicate anonymous transaction when AUTO_POSITION = 1, at file {#p1}, position %lld.",
	],
	[
		"code"      => 3114,
		"symbol"    => "ER_CANT_REPLICATE_ANONYMOUS_WITH_GTID_MODE_ON",
		"sql_state" => "HY000",
		"template"  => "Cannot replicate anonymous transaction when @@GLOBAL.GTID_MODE = ON, at file {#p1}, position %lld.",
	],
	[
		"code"      => 3115,
		"symbol"    => "ER_CANT_REPLICATE_GTID_WITH_GTID_MODE_OFF",
		"sql_state" => "HY000",
		"template"  => "Cannot replicate GTID-transaction when @@GLOBAL.GTID_MODE = OFF, at file {#p1}, position %lld.",
	],
	[
		"code"      => 3116,
		"symbol"    => "ER_CANT_SET_ENFORCE_GTID_CONSISTENCY_ON_WITH_ONGOING_GTID_VIOLATING_TRANSACTIONS",
		"sql_state" => "HY000",
		"template"  => "Cannot set ENFORCE_GTID_CONSISTENCY = ON because there are ongoing transactions that violate GTID consistency.",
	],
	[
		"code"      => 3117,
		"symbol"    => "ER_SET_ENFORCE_GTID_CONSISTENCY_WARN_WITH_ONGOING_GTID_VIOLATING_TRANSACTIONS",
		"sql_state" => "HY000",
		"template"  => "There are ongoing transactions that violate GTID consistency.",
	],
	[
		"code"      => 3118,
		"symbol"    => "ER_ACCOUNT_HAS_BEEN_LOCKED",
		"sql_state" => "HY000",
		"template"  => "Access denied for user '{#p1}'@'{#p2}'. Account is locked.",
	],
	[
		"code"      => 3119,
		"symbol"    => "ER_WRONG_TABLESPACE_NAME",
		"sql_state" => "42000",
		"template"  => "Incorrect tablespace name `{#p1}`",
	],
	[
		"code"      => 3120,
		"symbol"    => "ER_TABLESPACE_IS_NOT_EMPTY",
		"sql_state" => "HY000",
		"template"  => "Tablespace `{#p1}` is not empty.",
	],
	[
		"code"      => 3121,
		"symbol"    => "ER_WRONG_FILE_NAME",
		"sql_state" => "HY000",
		"template"  => "Incorrect File Name '{#p1}'.",
	],
	[
		"code"      => 3122,
		"symbol"    => "ER_BOOST_GEOMETRY_INCONSISTENT_TURNS_EXCEPTION",
		"sql_state" => "HY000",
		"template"  => "Inconsistent intersection points.",
	],
	[
		"code"      => 3123,
		"symbol"    => "ER_WARN_OPTIMIZER_HINT_SYNTAX_ERROR",
		"sql_state" => "HY000",
		"template"  => "Optimizer hint syntax error",
	],
	[
		"code"      => 3124,
		"symbol"    => "ER_WARN_BAD_MAX_EXECUTION_TIME",
		"sql_state" => "HY000",
		"template"  => "Unsupported MAX_EXECUTION_TIME",
	],
	[
		"code"      => 3125,
		"symbol"    => "ER_WARN_UNSUPPORTED_MAX_EXECUTION_TIME",
		"sql_state" => "HY000",
		"template"  => "MAX_EXECUTION_TIME hint is supported by top-level standalone SELECT statements only",
	],
	[
		"code"      => 3126,
		"symbol"    => "ER_WARN_CONFLICTING_HINT",
		"sql_state" => "HY000",
		"template"  => "Hint {#p1} is ignored as conflicting/duplicated",
	],
	[
		"code"      => 3127,
		"symbol"    => "ER_WARN_UNKNOWN_QB_NAME",
		"sql_state" => "HY000",
		"template"  => "Query block name {#p1} is not found for {#p2} hint",
	],
	[
		"code"      => 3128,
		"symbol"    => "ER_UNRESOLVED_HINT_NAME",
		"sql_state" => "HY000",
		"template"  => "Unresolved name {#p1} for {#p2} hint",
	],
	[
		"code"      => 3129,
		"symbol"    => "ER_WARN_DEPRECATED_SQLMODE_UNSET",
		"sql_state" => "HY000",
		"template"  => "Unsetting sql mode '{#p1}' is deprecated. It will be made read-only in a future release.",
	],
	[
		"code"      => 3129,
		"symbol"    => "ER_WARN_ON_MODIFYING_GTID_EXECUTED_TABLE",
		"sql_state" => "HY000",
		"template"  => "Please do not modify the {#p1} table. This is a mysql internal system table to store GTIDs for committed transactions. Modifying it can lead to an inconsistent GTID state.",
	],
	[
		"code"      => 3130,
		"symbol"    => "ER_PLUGGABLE_PROTOCOL_COMMAND_NOT_SUPPORTED",
		"sql_state" => "HY000",
		"template"  => "Command not supported by pluggable protocols",
	],
	[
		"code"      => 3131,
		"symbol"    => "ER_LOCKING_SERVICE_WRONG_NAME",
		"sql_state" => "42000",
		"template"  => "Incorrect locking service lock name '{#p1}'.",
	],
	[
		"code"      => 3132,
		"symbol"    => "ER_LOCKING_SERVICE_DEADLOCK",
		"sql_state" => "HY000",
		"template"  => "Deadlock found when trying to get locking service lock; try releasing locks and restarting lock acquisition.",
	],
	[
		"code"      => 3133,
		"symbol"    => "ER_LOCKING_SERVICE_TIMEOUT",
		"sql_state" => "HY000",
		"template"  => "Service lock wait timeout exceeded.",
	],
	[
		"code"      => 3134,
		"symbol"    => "ER_GIS_MAX_POINTS_IN_GEOMETRY_OVERFLOWED",
		"sql_state" => "HY000",
		"template"  => "Parameter {#p1} exceeds the maximum number of points in a geometry ({p2}) in function {#p3}.",
	],
	[
		"code"      => 3135,
		"symbol"    => "ER_SQL_MODE_MERGED",
		"sql_state" => "HY000",
		"template"  => "'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.",
	],
	[
		"code"      => 3136,
		"symbol"    => "ER_VTOKEN_PLUGIN_TOKEN_MISMATCH",
		"sql_state" => "HY000",
		"template"  => "Version token mismatch for %.*s. Correct value %.*s",
	],
	[
		"code"      => 3137,
		"symbol"    => "ER_VTOKEN_PLUGIN_TOKEN_NOT_FOUND",
		"sql_state" => "HY000",
		"template"  => "Version token %.*s not found.",
	],
	[
		"code"      => 3138,
		"symbol"    => "ER_CANT_SET_VARIABLE_WHEN_OWNING_GTID",
		"sql_state" => "HY000",
		"template"  => "Variable {#p1} cannot be changed by a client that owns a GTID. The client owns {#p2}. Ownership is released on COMMIT or ROLLBACK.",
	],
	[
		"code"      => 3139,
		"symbol"    => "ER_SLAVE_CHANNEL_OPERATION_NOT_ALLOWED",
		"sql_state" => "HY000",
		"template"  => "{#p1} cannot be performed on channel '{#p2}'.",
	],
	[
		"code"      => 3140,
		"symbol"    => "ER_INVALID_JSON_TEXT",
		"sql_state" => "22032",
		"template"  => "Invalid JSON text: \"{#p1}\" at position {p2} in value for column '{#p3}'.",
	],
	[
		"code"      => 3141,
		"symbol"    => "ER_INVALID_JSON_TEXT_IN_PARAM",
		"sql_state" => "22032",
		"template"  => "Invalid JSON text in argument {p1} to function {#p2}: \"{#p3}\" at position {p4}.{#p5}",
	],
	[
		"code"      => 3142,
		"symbol"    => "ER_INVALID_JSON_BINARY_DATA",
		"sql_state" => "HY000",
		"template"  => "The JSON binary value contains invalid data.",
	],
	[
		"code"      => 3143,
		"symbol"    => "ER_INVALID_JSON_PATH",
		"sql_state" => "42000",
		"template"  => "Invalid JSON path expression. The error is around character position {p1}.{#p2}",
	],
	[
		"code"      => 3144,
		"symbol"    => "ER_INVALID_JSON_CHARSET",
		"sql_state" => "22032",
		"template"  => "Cannot create a JSON value from a string with CHARACTER SET '{#p1}'.",
	],
	[
		"code"      => 3145,
		"symbol"    => "ER_INVALID_JSON_CHARSET_IN_FUNCTION",
		"sql_state" => "22032",
		"template"  => "Invalid JSON character data provided to function {#p1}: '{#p2}'; utf8 is required.",
	],
	[
		"code"      => 3146,
		"symbol"    => "ER_INVALID_TYPE_FOR_JSON",
		"sql_state" => "22032",
		"template"  => "Invalid data type for JSON data in argument {p1} to function {#p2}; a JSON string or JSON type is required.",
	],
	[
		"code"      => 3147,
		"symbol"    => "ER_INVALID_CAST_TO_JSON",
		"sql_state" => "22032",
		"template"  => "Cannot CAST value to JSON.",
	],
	[
		"code"      => 3148,
		"symbol"    => "ER_INVALID_JSON_PATH_CHARSET",
		"sql_state" => "42000",
		"template"  => "A path expression must be encoded in the utf8 character set. The path expression '{#p1}' is encoded in character set '{#p2}'.",
	],
	[
		"code"      => 3149,
		"symbol"    => "ER_INVALID_JSON_PATH_WILDCARD",
		"sql_state" => "42000",
		"template"  => "In this situation, path expressions may not contain the * and ** tokens.",
	],
	[
		"code"      => 3150,
		"symbol"    => "ER_JSON_VALUE_TOO_BIG",
		"sql_state" => "22032",
		"template"  => "The JSON value is too big to be stored in a JSON column.",
	],
	[
		"code"      => 3151,
		"symbol"    => "ER_JSON_KEY_TOO_BIG",
		"sql_state" => "22032",
		"template"  => "The JSON object contains a key name that is too long.",
	],
	[
		"code"      => 3152,
		"symbol"    => "ER_JSON_USED_AS_KEY",
		"sql_state" => "42000",
		"template"  => "JSON column '{#p1}' cannot be used in key specification.",
	],
	[
		"code"      => 3153,
		"symbol"    => "ER_JSON_VACUOUS_PATH",
		"sql_state" => "42000",
		"template"  => "The path expression '\$' is not allowed in this context.",
	],
	[
		"code"      => 3154,
		"symbol"    => "ER_JSON_BAD_ONE_OR_ALL_ARG",
		"sql_state" => "42000",
		"template"  => "The oneOrAll argument to {#p1} may take these values: 'one' or 'all'.",
	],
	[
		"code"      => 3155,
		"symbol"    => "ER_NUMERIC_JSON_VALUE_OUT_OF_RANGE",
		"sql_state" => "22003",
		"template"  => "Out of range JSON value for CAST to {#p1}{#p2} from column {#p3} at row {p4}",
	],
	[
		"code"      => 3156,
		"symbol"    => "ER_INVALID_JSON_VALUE_FOR_CAST",
		"sql_state" => "22018",
		"template"  => "Invalid JSON value for CAST to {#p1}{#p2} from column {#p3} at row {p4}",
	],
	[
		"code"      => 3157,
		"symbol"    => "ER_JSON_DOCUMENT_TOO_DEEP",
		"sql_state" => "22032",
		"template"  => "The JSON document exceeds the maximum depth.",
	],
	[
		"code"      => 3158,
		"symbol"    => "ER_JSON_DOCUMENT_NULL_KEY",
		"sql_state" => "22032",
		"template"  => "JSON documents may not contain NULL member names.",
	],
	[
		"code"      => 3159,
		"symbol"    => "ER_SECURE_TRANSPORT_REQUIRED",
		"sql_state" => "HY000",
		"template"  => "Connections using insecure transport are prohibited while --require_secure_transport=ON.",
	],
	[
		"code"      => 3160,
		"symbol"    => "ER_NO_SECURE_TRANSPORTS_CONFIGURED",
		"sql_state" => "HY000",
		"template"  => "No secure transports (SSL or Shared Memory) are configured, unable to set --require_secure_transport=ON.",
	],
	[
		"code"      => 3161,
		"symbol"    => "ER_DISABLED_STORAGE_ENGINE",
		"sql_state" => "HY000",
		"template"  => "Storage engine {#p1} is disabled (Table creation is disallowed).",
	],
	[
		"code"      => 3162,
		"symbol"    => "ER_USER_DOES_NOT_EXIST",
		"sql_state" => "HY000",
		"template"  => "User {#p1} does not exist.",
	],
	[
		"code"      => 3163,
		"symbol"    => "ER_USER_ALREADY_EXISTS",
		"sql_state" => "HY000",
		"template"  => "User {#p1} already exists.",
	],
	[
		"code"      => 3164,
		"symbol"    => "ER_AUDIT_API_ABORT",
		"sql_state" => "HY000",
		"template"  => "Aborted by Audit API ('{#p1}';{p2}).",
	],
	[
		"code"      => 3165,
		"symbol"    => "ER_INVALID_JSON_PATH_ARRAY_CELL",
		"sql_state" => "42000",
		"template"  => "A path expression is not a path to a cell in an array.",
	],
	[
		"code"      => 3166,
		"symbol"    => "ER_BUFPOOL_RESIZE_INPROGRESS",
		"sql_state" => "HY000",
		"template"  => "Another buffer pool resize is already in progress.",
	],
	[
		"code"      => 3167,
		"symbol"    => "ER_FEATURE_DISABLED_SEE_DOC",
		"sql_state" => "HY000",
		"template"  => "The '{#p1}' feature is disabled; see the documentation for '{#p2}'",
	],
	[
		"code"      => 3168,
		"symbol"    => "ER_SERVER_ISNT_AVAILABLE",
		"sql_state" => "HY000",
		"template"  => "Server isn't available",
	],
	[
		"code"      => 3169,
		"symbol"    => "ER_SESSION_WAS_KILLED",
		"sql_state" => "HY000",
		"template"  => "Session was killed",
	],
	[
		"code"      => 3170,
		"symbol"    => "ER_CAPACITY_EXCEEDED",
		"sql_state" => "HY000",
		"template"  => "Memory capacity of {bytes} bytes for '{#param}' exceeded. {#message}",
	],
	[
		"code"      => 3171,
		"symbol"    => "ER_CAPACITY_EXCEEDED_IN_RANGE_OPTIMIZER",
		"sql_state" => "HY000",
		"template"  => "Range optimization was not done for this query.",
	],
	[
		"code"      => 3172,
		"symbol"    => "ER_TABLE_NEEDS_UPG_PART",
		"sql_state" => "HY000",
		"template"  => "Partitioning upgrade required. Please dump/reload to fix it or do: ALTER TABLE `{#p1}`.`{#p2}` UPGRADE PARTITIONING",
	],
	[
		"code"      => 3173,
		"symbol"    => "ER_CANT_WAIT_FOR_EXECUTED_GTID_SET_WHILE_OWNING_A_GTID",
		"sql_state" => "HY000",
		"template"  => "The client holds ownership of the GTID {#p1}. Therefore, WAIT_FOR_EXECUTED_GTID_SET cannot wait for this GTID.",
	],
	[
		"code"      => 3174,
		"symbol"    => "ER_CANNOT_ADD_FOREIGN_BASE_COL_VIRTUAL",
		"sql_state" => "HY000",
		"template"  => "Cannot add foreign key on the base column of indexed virtual column.",
	],
	[
		"code"      => 3175,
		"symbol"    => "ER_CANNOT_CREATE_VIRTUAL_INDEX_CONSTRAINT",
		"sql_state" => "HY000",
		"template"  => "Cannot create index on virtual column whose base column has foreign constraint.",
	],
	[
		"code"      => 3176,
		"symbol"    => "ER_ERROR_ON_MODIFYING_GTID_EXECUTED_TABLE",
		"sql_state" => "HY000",
		"template"  => "Please do not modify the {#p1} table with an XA transaction. This is an internal system table used to store GTIDs for committed transactions. Although modifying it can lead to an inconsistent GTID state, if neccessary you can modify it with a non-XA transaction.",
	],
	[
		"code"      => 3177,
		"symbol"    => "ER_LOCK_REFUSED_BY_ENGINE",
		"sql_state" => "HY000",
		"template"  => "Lock acquisition refused by storage engine.",
	],
	[
		"code"      => 3178,
		"symbol"    => "ER_UNSUPPORTED_ALTER_ONLINE_ON_VIRTUAL_COLUMN",
		"sql_state" => "HY000",
		"template"  => "ADD COLUMN col...VIRTUAL, ADD INDEX(col)",
	],
	[
		"code"      => 3179,
		"symbol"    => "ER_MASTER_KEY_ROTATION_NOT_SUPPORTED_BY_SE",
		"sql_state" => "HY000",
		"template"  => "Master key rotation is not supported by storage engine.",
	],
	[
		"code"      => 3180,
		"symbol"    => "ER_MASTER_KEY_ROTATION_ERROR_BY_SE",
		"sql_state" => "HY000",
		"template"  => "Encryption key rotation error reported by SE: {#p1}",
	],
	[
		"code"      => 3181,
		"symbol"    => "ER_MASTER_KEY_ROTATION_BINLOG_FAILED",
		"sql_state" => "HY000",
		"template"  => "Write to binlog failed. However, master key rotation has been completed successfully.",
	],
	[
		"code"      => 3182,
		"symbol"    => "ER_MASTER_KEY_ROTATION_SE_UNAVAILABLE",
		"sql_state" => "HY000",
		"template"  => "Storage engine is not available.",
	],
	[
		"code"      => 3183,
		"symbol"    => "ER_TABLESPACE_CANNOT_ENCRYPT",
		"sql_state" => "HY000",
		"template"  => "This tablespace can't be encrypted.",
	],
	[
		"code"      => 3184,
		"symbol"    => "ER_INVALID_ENCRYPTION_OPTION",
		"sql_state" => "HY000",
		"template"  => "Invalid encryption option.",
	],
	[
		"code"      => 3185,
		"symbol"    => "ER_CANNOT_FIND_KEY_IN_KEYRING",
		"sql_state" => "HY000",
		"template"  => "Can't find master key from keyring, please check in the server log if a keyring plugin is loaded and initialized successfully.",
	],
	[
		"code"      => 3186,
		"symbol"    => "ER_CAPACITY_EXCEEDED_IN_PARSER",
		"sql_state" => "HY000",
		"template"  => "Parser bailed out for this query.",
	],
	[
		"code"      => 3187,
		"symbol"    => "ER_UNSUPPORTED_ALTER_ENCRYPTION_INPLACE",
		"sql_state" => "HY000",
		"template"  => "Cannot alter encryption attribute by inplace algorithm.",
	],
	[
		"code"      => 3188,
		"symbol"    => "ER_KEYRING_UDF_KEYRING_SERVICE_ERROR",
		"sql_state" => "HY000",
		"template"  => "Function '{#p1}' failed because underlying keyring service returned an error. Please check if a keyring plugin is installed and that provided arguments are valid for the keyring you are using.",
	],
	[
		"code"      => 3189,
		"symbol"    => "ER_USER_COLUMN_OLD_LENGTH",
		"sql_state" => "HY000",
		"template"  => "It seems that your db schema is old. The {#p1} column is 77 characters long and should be 93 characters long. Please run mysql_upgrade.",
	],
	[
		"code"      => 3190,
		"symbol"    => "ER_CANT_RESET_MASTER",
		"sql_state" => "HY000",
		"template"  => "RESET MASTER is not allowed because {#p1}.",
	],
	[
		"code"      => 3191,
		"symbol"    => "ER_GROUP_REPLICATION_MAX_GROUP_SIZE",
		"sql_state" => "HY000",
		"template"  => "The START GROUP_REPLICATION command failed since the group already has 9 members.",
	],
	[
		"code"      => 3192,
		"symbol"    => "ER_CANNOT_ADD_FOREIGN_BASE_COL_STORED",
		"sql_state" => "HY000",
		"template"  => "Cannot add foreign key on the base column of stored column.",
	],
	[
		"code"      => 3193,
		"symbol"    => "ER_TABLE_REFERENCED",
		"sql_state" => "HY000",
		"template"  => "Cannot complete the operation because table is referenced by another connection.",
	],
	[
		"code"      => 3194,
		"symbol"    => "ER_PARTITION_ENGINE_DEPRECATED_FOR_TABLE",
		"sql_state" => "HY000",
		"template"  => "The partition engine, used by table '{#p1}.{#p2}', is deprecated and will be removed in a future release. Please use native partitioning instead.",
	],
	[
		"code"      => 3195,
		"symbol"    => "ER_WARN_USING_GEOMFROMWKB_TO_SET_SRID_ZERO",
		"sql_state" => "01000",
		"template"  => "{#p1}(geometry) is deprecated and will be replaced by st_srid(geometry, 0) in a future version. Use {#p2}(st_aswkb(geometry), 0) instead.",
	],
	[
		"code"      => 3196,
		"symbol"    => "ER_WARN_USING_GEOMFROMWKB_TO_SET_SRID",
		"sql_state" => "01000",
		"template"  => "{#p1}(geometry, srid) is deprecated and will be replaced by st_srid(geometry, srid) in a future version. Use {#p2}(st_aswkb(geometry), srid) instead.",
	],
	[
		"code"      => 3197,
		"symbol"    => "ER_XA_RETRY",
		"sql_state" => "HY000",
		"template"  => "The resource manager is not able to commit the transaction branch at this time. Please retry later.",
	],
	[
		"code"      => 3198,
		"symbol"    => "ER_KEYRING_AWS_UDF_AWS_KMS_ERROR",
		"sql_state" => "HY000",
		"template"  => "Function {#p1} failed due to: {#p2}.",
	],
	[
		"code"      => 3199,
		"symbol"    => "ER_BINLOG_UNSAFE_XA",
		"sql_state" => "HY000",
		"template"  => "Statement is unsafe because it is being used inside a XA transaction. Concurrent XA transactions may deadlock on slaves when replicated using statements.",
	],
	[
		"code"      => 3201,
		"symbol"    => "ER_KEYRING_MIGRATION_FAILURE",
		"sql_state" => "HY000",
		"template"  => "Can not perform keyring migration : {#p1}",
	],
	[
		"code"      => 3202,
		"symbol"    => "ER_KEYRING_ACCESS_DENIED_ERROR",
		"sql_state" => "42000",
		"template"  => "Access denied; you need {#p1} privileges for this operation",
	],
	[
		"code"      => 3203,
		"symbol"    => "ER_KEYRING_MIGRATION_STATUS",
		"sql_state" => "HY000",
		"template"  => "Keyring migration {#p1}.",
	],
	[
		"code"      => 3204,
		"symbol"    => "ER_PLUGIN_FAILED_TO_OPEN_TABLES",
		"sql_state" => "HY000",
		"template"  => "Failed to open the {#p1} filter tables.",
	],
	[
		"code"      => 3205,
		"symbol"    => "ER_PLUGIN_FAILED_TO_OPEN_TABLE",
		"sql_state" => "HY000",
		"template"  => "Failed to open '{#p1}.{#p2}' {#p3} table.",
	],
	[
		"code"      => 3206,
		"symbol"    => "ER_AUDIT_LOG_NO_KEYRING_PLUGIN_INSTALLED",
		"sql_state" => "HY000",
		"template"  => "No keyring plugin installed.",
	],
	[
		"code"      => 3207,
		"symbol"    => "ER_AUDIT_LOG_ENCRYPTION_PASSWORD_HAS_NOT_BEEN_SET",
		"sql_state" => "HY000",
		"template"  => "Audit log encryption password has not been set; it will be generated automatically. Use audit_log_encryption_password_get to obtain the password or audit_log_encryption_password_set to set a new one.",
	],
	[
		"code"      => 3208,
		"symbol"    => "ER_AUDIT_LOG_COULD_NOT_CREATE_AES_KEY",
		"sql_state" => "HY000",
		"template"  => "Could not create AES key. OpenSSL's EVP_BytesToKey function failed.",
	],
	[
		"code"      => 3209,
		"symbol"    => "ER_AUDIT_LOG_ENCRYPTION_PASSWORD_CANNOT_BE_FETCHED",
		"sql_state" => "HY000",
		"template"  => "Audit log encryption password cannot be fetched from the keyring. Password used so far is used for encryption.",
	],
	[
		"code"      => 3210,
		"symbol"    => "ER_AUDIT_LOG_JSON_FILTERING_NOT_ENABLED",
		"sql_state" => "HY000",
		"template"  => "Audit Log filtering has not been installed.",
	],
	[
		"code"      => 3211,
		"symbol"    => "ER_AUDIT_LOG_UDF_INSUFFICIENT_PRIVILEGE",
		"sql_state" => "HY000",
		"template"  => "Request ignored for '{#p1}'@'{#p2}'. SUPER_ACL needed to perform operation",
	],
	[
		"code"      => 3212,
		"symbol"    => "ER_AUDIT_LOG_SUPER_PRIVILEGE_REQUIRED",
		"sql_state" => "HY000",
		"template"  => "SUPER privilege required for '{#p1}'@'{#p2}' user.",
	],
	[
		"code"      => 3213,
		"symbol"    => "ER_COULD_NOT_REINITIALIZE_AUDIT_LOG_FILTERS",
		"sql_state" => "HY000",
		"template"  => "Could not reinitialize audit log filters.",
	],
	[
		"code"      => 3214,
		"symbol"    => "ER_AUDIT_LOG_UDF_INVALID_ARGUMENT_TYPE",
		"sql_state" => "HY000",
		"template"  => "Invalid argument type",
	],
	[
		"code"      => 3215,
		"symbol"    => "ER_AUDIT_LOG_UDF_INVALID_ARGUMENT_COUNT",
		"sql_state" => "HY000",
		"template"  => "Invalid argument count",
	],
	[
		"code"      => 3216,
		"symbol"    => "ER_AUDIT_LOG_HAS_NOT_BEEN_INSTALLED",
		"sql_state" => "HY000",
		"template"  => "audit_log plugin has not been installed using INSTALL PLUGIN syntax.",
	],
	[
		"code"      => 3217,
		"symbol"    => "ER_AUDIT_LOG_UDF_READ_INVALID_MAX_ARRAY_LENGTH_ARG_TYPE",
		"sql_state" => "HY000",
		"template"  => "Invalid \"max_array_length\" argument type.",
	],
	[
		"code"      => 3218,
		"symbol"    => "ER_AUDIT_LOG_UDF_READ_INVALID_MAX_ARRAY_LENGTH_ARG_VALUE",
		"sql_state" => "HY000",
		"template"  => "Invalid \"max_array_length\" argument value.",
	],
	[
		"code"      => 3220,
		"symbol"    => "ER_AUDIT_LOG_JSON_FILTER_NAME_CANNOT_BE_EMPTY",
		"sql_state" => "HY000",
		"template"  => "Filter name cannot be empty.",
	],
	[
		"code"      => 3221,
		"symbol"    => "ER_AUDIT_LOG_JSON_USER_NAME_CANNOT_BE_EMPTY",
		"sql_state" => "HY000",
		"template"  => "User cannot be empty.",
	],
	[
		"code"      => 3222,
		"symbol"    => "ER_AUDIT_LOG_JSON_FILTER_DOES_NOT_EXISTS",
		"sql_state" => "HY000",
		"template"  => "Specified filter has not been found.",
	],
	[
		"code"      => 3223,
		"symbol"    => "ER_AUDIT_LOG_USER_FIRST_CHARACTER_MUST_BE_ALPHANUMERIC",
		"sql_state" => "HY000",
		"template"  => "First character of the user name must be alphanumeric.",
	],
	[
		"code"      => 3224,
		"symbol"    => "ER_AUDIT_LOG_USER_NAME_INVALID_CHARACTER",
		"sql_state" => "HY000",
		"template"  => "Invalid character in the user name.",
	],
	[
		"code"      => 3225,
		"symbol"    => "ER_AUDIT_LOG_HOST_NAME_INVALID_CHARACTER",
		"sql_state" => "HY000",
		"template"  => "Invalid character in the host name.",
	],
	[
		"code"      => 3226,
		"symbol"    => "WARN_DEPRECATED_MAXDB_SQL_MODE_FOR_TIMESTAMP",
		"sql_state" => "HY000",
		"template"  => "With the MAXDB SQL mode enabled, TIMESTAMP is identical with DATETIME. The MAXDB SQL mode is deprecated and will be removed in a future release. Please disable the MAXDB SQL mode and use DATETIME instead.",
	],
	[
		"code"      => 3227,
		"symbol"    => "ER_XA_REPLICATION_FILTERS",
		"sql_state" => "HY000",
		"template"  => "The use of replication filters with XA transactions is not supported, and can lead to an undefined state in the replication slave.",
	],
	[
		"code"      => 3228,
		"symbol"    => "ER_CANT_OPEN_ERROR_LOG",
		"sql_state" => "HY000",
		"template"  => "Could not open file '{#p1}' for error logging{#p2}{#p3}",
	],
	[
		"code"      => 3229,
		"symbol"    => "ER_GROUPING_ON_TIMESTAMP_IN_DST",
		"sql_state" => "HY000",
		"template"  => "Grouping on temporal is non-deterministic for timezones having DST. Please consider switching to UTC for this query.",
	],
	[
		"code"      => 3230,
		"symbol"    => "ER_CANT_START_SERVER_NAMED_PIPE",
		"sql_state" => "HY000",
		"template"  => "Can't start server : Named Pipe \"{#p1}\" already in use.",
	],
];

return array_merge($previous, $new);
